#:include "common/diameter.fypp"

module ${MODEL_NAME}$

    use yaeos__tapenade_ar_api, only: ArModelTapenade
    use yaeos__tapenade_interfaces
    use yaeos, only: R

    implicit none

    !type, extends(ArModelTapenade) :: ${MODEL_NAME}$
    type :: ${MODEL_NAME}$

        @:DIAMETER_TYPE_MEMBERS()

    !contains
    !    procedure :: ar
    !    procedure :: ar_d
    !    procedure :: ar_b
    !    procedure :: ar_d_b
    !    procedure :: ar_d_d
    !    procedure :: v0

    end type ${MODEL_NAME}$

contains

    type(${MODEL_NAME}$) function setup_model( &
        sigma, &
        epsilon_k &
    )

        @:DIAMETER_SETUP_ARGS()

        @:DIAMETER_SETUP_BODY()

    end function setup_model


    subroutine ar(model, n, v, t, arval)

        type(${MODEL_NAME}$), intent(in) :: model

        real(8), intent(in) :: n(:)
        real(8), intent(in) :: v
        real(8), intent(in) :: t

        real(8), intent(out) :: arval

        @:DIAMETER_AR_LOCALS()

        @:DIAMETER_AR_CODE()

        ! =====================================================
        ! Acá irá el cálculo de Ar
        ! =====================================================

        arval = 0.0_8

    end subroutine ar


    pure function volume_initializer(n, p, t) result(v0)

        real(8), intent(in) :: n(:)
        real(8), intent(in) :: p
        real(8), intent(in) :: t

        real(8) :: v0

        v0 = sum(n)

    end function volume_initializer

end module ${MODEL_NAME}$