#:mute
#:include "code/attributes.fypp"
!    - attributes(ATTRIBUTES)
!    - attributes_in_helmholtz(ATTRIBUTES)
!    - setup_signature(ATTRIBUTES)
!    - setup_body(ATTRIBUTES)
#:include "code/diameter.fypp"
!    - diameter_declaration(DIAMETER)
!    - diameter(DIAMETER)
#:include "code/zetas.fypp"
!    - zetas_declaration(ZETAS)
!    - zetas(ZETAS)
#:include "code/ar_hard_sphere.fypp"
!    - ar_hard_sphere_declaration(AR_HARD_SPHERE)
!    - ar_hard_sphere(AR_HARD_SPHERE)
#:include "code/ar_chain.fypp"
!    - ar_chain_declaration(AR_CHAIN)
!    - ar_chain(AR_CHAIN)
#:include "code/ar_dispersion.fypp"
!    - ar_dispersion_declaration(AR_DISPERSION)
!    - ar_dispersion(AR_DISPERSION)
#:endmute
module yaeos__models_ar_saft_modelnamesedme
   use yaeos__tapenade_ar_api, only: ArModelTapenade
   use yaeos__tapenade_interfaces
   use yaeos, only: R
   implicit none

   ! ---------------------------------------------------------------------------
   ! PC-SAFT UNIVERSAL CONSTANTS (Gross & Sadowski, 2001, Table A1)
   ! ---------------------------------------------------------------------------
   real(8), dimension(0:2, 0:6) :: A_COEFFS = reshape([ &
      0.9105631445, -0.3084016918, -0.0906148351, &
      0.6361281449 , 0.1860531159 , 0.4527842806,  &
      2.6861347891 , -2.5030047259, 0.5962700728, &
      -26.547362491, 21.419793629 ,-1.7241829131,&
      97.759208784 ,-65.255885330 ,-4.1302112531,&
      -159.59154087, 83.318680481 ,13.776631870, &
      91.297774084 ,-33.746922930 ,-8.6728470368 ], [3, 7])

   real(8), dimension(0:2, 0:6) :: B_COEFFS = reshape([ &
      0.7240946941, -0.5755498075, 0.0976883116, &
      2.2382791861, 0.6995095521, -0.2557574982, &
      -4.0025849485, 3.8925673390, -9.1558561530, &
      -21.003576815, -17.215471648, 20.642075974, &
      26.855641363, 192.67226447, -38.804430052, &
      206.55133841, -161.82646165, 93.626774077, &
      -355.60235612, -165.20769346, -29.666905585], [3, 7])

   type :: ModelNameSedMe
      $:attributes(ATTRIBUTES)
   end type ModelNameSedMe

   ! Module private constants
   real(8), parameter :: PI = 3.14159265359_8
   real(8), parameter :: N_AVO = 6.02214076e23_8

   ! Conversion factor:
   ! Zeta must be dimensionless. V comes in Liters. Sigma in Angstroms.
   ! 1 L = 10^27 A^3. rho_num [1/A^3] = (n [mol] * N_AVO) / (V [L] * 10^27)
   real(8), parameter :: UNITS_FACTOR = 0.000602214086_8

contains
   subroutine ar(model, n, v, t, arval)
      type(ModelNameSedMe), intent(in) :: model
      real(8), intent(in) :: n(:), v, t
      real(8), intent(out) :: arval

      ! Auxiliars
      integer :: i, j, k
      real(8) :: x(size(n)) ! Mole fractions
      real(8) :: n_tot ! Total moles
      integer :: nc ! Number of components
      real(8) :: m_average ! Average number of segments

      ! Internal variables declarations
      ! Diameter declarations
      $:diameter_declaration(DIAMETER)
      ! Zetas declarations
      $:zetas_declaration(ZETAS)
      ! Ar hard-sphere contribution declarations
      $:ar_hard_sphere_declaration(AR_HARD_SPHERE)
      ! Ar chain contribution declarations
      $:ar_chain_declaration(AR_CHAIN)
      ! Ar dispersion contribution declarations
      $:ar_dispersion_declaration(AR_DISPERSION)
      ! Attributes declarations as variables
      $:attributes_in_helmholtz(ATTRIBUTES)

      ! Residual Helmholtz free energy calculation
      x = n / sum(n)  ! Mole fractions
      n_tot = sum(n)  ! Total moles
      nc = size(n)    ! Number of components

      ! Diameter calculation
      $:diameter(DIAMETER)
      
      ! Zetas calculation
      $:zetas(ZETAS)

      ! Ar hard-sphere contribution
      $:ar_hard_sphere(AR_HARD_SPHERE)

      ! Ar chain contribution
      $:ar_chain(AR_CHAIN)

      ! Ar dispersion contribution
      $:ar_dispersion(AR_DISPERSION)

      ! Final evaluation
      m_average = 0.0_8
      do i = 1, nc
         m_average = m_average + x(i)*m(i) ! Segment average
      end do

      arval = (R * T * n_tot) * (m_average * ar_hs + ar_chain + ar_dispersion)
   end subroutine ar

   ! PUT setup and get_v0 here after tapenade
end module yaeos__models_ar_saft_modelnamesedme
