aijTder – yaeos
aijTder Subroutine
MPL
33 statements
Source File
public subroutine aijTder(ntd, nc, T, aij, daijdT, daijdT2)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ntd
integer, intent(in) :: nc
real(kind=pr), intent(in) :: T
real(kind=pr), intent(out) :: aij(nc,nc)
real(kind=pr), intent(out) :: daijdT(nc,nc)
real(kind=pr), intent(out) :: daijdT2(nc,nc)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: ai(nc)
real(kind=pr), public :: aux(nc,nc)
real(kind=pr), public :: daidT(nc)
real(kind=pr), public :: daidT2(nc)
integer, public :: i
integer, public :: j
real(kind=pr), public :: ratK(nc,nc)
Call graph
aijtder calls atder
dandtnder calls aijtder
helmrkpr calls dandtnder
helmsrkpr calls dandtnder
ar_rkpr calls helmrkpr
ar_srkpr calls helmsrkpr