Ar_impl – yaeos
Ar_impl Function
MPL
38 statements
Source File
private function Ar_impl(self, n, V, T) result(ar_total)
Type Bound
PcSaft
Arguments
Type Intent Optional Attributes Name
class(PcSaft) :: self
type(hyperdual), intent(in) :: n(:)
type(hyperdual), intent(in) :: V
type(hyperdual), intent(in) :: T
Return Value type(hyperdual)
Calls
Variables
Type Visibility Attributes Name Initial
type(hyperdual), private :: a_assoc
type(hyperdual), private :: a_chain
type(hyperdual), private :: a_disp
type(hyperdual), private :: a_hs
type(hyperdual), private :: d(size(n))
type(hyperdual), private :: eta
integer, private :: i
type(hyperdual), private :: m_ave
type(hyperdual), private :: n_tot
integer, private :: nc
type(hyperdual), private :: rho
type(hyperdual), private :: x(size(n))
type(hyperdual), private :: zeta(0:3)
Call graph
ar_impl calls calculate_association, calculate_chain, calculate_dispersion, calculate_hard_sphere, calculate_zetas