ar_srkpr – yaeos
ar_srkpr Subroutine
MPL
18 statements
Source File
public subroutine ar_srkpr(z, v, t, ar, arv, artv, arv2, Arn, ArVn, ArTn, Arn2)
Wrapper subroutine to the SRK/PR Residula Helmholtz function to use the general interface
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: z(:)
Number of moles
real(kind=pr), intent(in) :: v
Volume [L]
real(kind=pr), intent(in) :: t
Temperature [K]
real(kind=pr), intent(out) :: ar
Residual Helmholtz
real(kind=pr), intent(out) :: arv
dAr/dV
real(kind=pr), intent(out) :: artv
dAr2/dTV
real(kind=pr), intent(out) :: arv2
dAr2/dV2
real(kind=pr), intent(out) :: Arn(size(z))
dAr/dn
real(kind=pr), intent(out) :: ArVn(size(z))
dAr2/dVn
real(kind=pr), intent(out) :: ArTn(size(z))
dAr2/dTn
real(kind=pr), intent(out) :: Arn2(size(z),size(z))
dAr2/dn2
Calls
Variables
Type Visibility Attributes Name Initial
integer, public :: nd
Compositional derivatives
integer, public :: nt
Temperature derivatives
Call graph
ar_srkpr calls helmsrkpr
helmsrkpr calls bnder, dandtnder
dandtnder calls aijtder
aijtder calls atder