arfun – yaeos
arfun Function
MPL
35 statements
Source File
public function arfun(self, n, v, t) result(arval)
Type Bound
Gerg2008
Arguments
Type Intent Optional Attributes Name
class(Gerg2008) :: self
type(hyperdual), intent(in) :: n(:)
type(hyperdual), intent(in) :: v
type(hyperdual), intent(in) :: t
Return Value type(hyperdual)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: Fij(size(n),size(n))
type(hyperdual), public :: Tr
type(hyperdual), public :: Vr
type(hyperdual), public :: X(size(n))
type(hyperdual), public :: aij
type(hyperdual), public :: ar_pures(size(n))
type(Gerg2008Binary), public :: binary
type(hyperdual), public :: delta
integer, public :: i
integer, public :: j
integer, public :: nc
type(Gerg2008Pure), public :: pures(size(n))
real(kind=pr), public :: rho_c(size(n))
type(hyperdual), public :: rho_r
type(hyperdual), public :: tau
Call graph
arfun calls ar_ij, ar_pure, reducing_functions