ArVnder – Yaeos
ArVnder Subroutine
MIT
14 statements
Source File
public subroutine ArVnder(nc, nder, ntemp, z, V, T, ar, arv, artv, arv2, Arn, ArVn, ArTn, Arn2)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nc
integer, intent(in) :: nder
integer, intent(in) :: ntemp
real(kind=pr), intent(in) :: z(nc)
real(kind=pr), intent(in) :: V
real(kind=pr), intent(in) :: T
real(kind=pr), intent(out) :: ar
real(kind=pr), intent(out) :: arv
real(kind=pr), intent(out) :: artv
real(kind=pr), intent(out) :: arv2
real(kind=pr), intent(out), dimension(size(z)) :: Arn
real(kind=pr), intent(out), dimension(size(z)) :: ArVn
real(kind=pr), intent(out), dimension(size(z)) :: ArTn
real(kind=pr), intent(out) :: Arn2(size(z),size(z))
Calls
Called by
Contents
None
Call graph
arvnder calls check
purefug_calc calls arvnder
vcalc calls arvnder
ztvtermo calls arvnder
termo calls arvnder, vcalc