betalimits – yaeos
betalimits Subroutine
MPL
21 statements
Source File
public subroutine betalimits(z, K, bmin, bmax)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: z(:)
real(kind=pr), intent(in) :: K(:)
real(kind=pr), intent(out) :: bmin
real(kind=pr), intent(out) :: bmax
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: in
integer, public :: ix
real(kind=pr), public, dimension(size(z)) :: vmax
real(kind=pr), public, dimension(size(z)) :: vmin
Call graph
flash calls betalimits, solve_rr
solve_rr calls betalimits