binary_llv_from_cep – yaeos
binary_llv_from_cep Function
MPL
81 statements
Source File
public function binary_llv_from_cep(model, cep) result(llv)
binary_llv_from_cep
Calculate the LLV line from a converged critical end point (CEP).
Description
From a converged critical end point (CEP) of a binary mixture, this function calculates the three-phase line (LLV) by solving the corresponding system of equations (defined at three_phase_line_F) at each point. To trace the whole line a continuation method is used to obtain good initial guesses for each point. The specification used to trace the line is initially the difference between the mole fractions of the two liquid phases, and then it is switched to temperature.
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Thermodynamic model to use
type(EquilibriumState), intent(in) :: cep
Converged critical end point.
Return Value type(BinaryThreePhase)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: F(nvars)
real(kind=pr), private :: P
real(kind=pr), private, allocatable :: Ps(:)
real(kind=pr), private :: S
real(kind=pr), private :: T
real(kind=pr), private, allocatable :: Ts(:)
real(kind=pr), private :: Vw
real(kind=pr), private :: Vx
real(kind=pr), private :: Vy
real(kind=pr), private :: X(nvars)
real(kind=pr), private :: dF(nvars,nvars)
real(kind=pr), private :: dFdS(nvars)
real(kind=pr), private :: dS
real(kind=pr), private :: dXdS(nvars)
real(kind=pr), private :: delta
real(kind=pr), private :: imin
integer, private :: iters
integer, private :: ns
integer, private, parameter :: nvars = 10
integer, private :: points
real(kind=pr), private :: w(2)
real(kind=pr), private :: xx(2)
real(kind=pr), private :: y(2)
Call graph
binary_llv_from_cep calls pressure, solve_system, three_phase_line_f_solve, volume
pressure calls residual_helmholtz
solve_system calls dgesv
three_phase_line_f_solve calls solve_system, three_phase_line_f
volume calls get_v0, newton
newton calls newton_1d
three_phase_line_f calls lnfug_vt
lnfug_vt calls residual_helmholtz