Bnder – yaeos
Bnder Subroutine
MPL
25 statements
Source File
public subroutine Bnder(nc, rn, Bmix, dBi, dBij)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nc
real(kind=pr), intent(in) :: rn(nc)
real(kind=pr), intent(out) :: Bmix
real(kind=pr), intent(out) :: dBi(nc)
real(kind=pr), intent(out) :: dBij(nc,nc)
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: aux(nc)
integer, public :: i
integer, public :: j
real(kind=pr), public :: totn
Call graph
cubic_v0 calls bnder
helmrkpr calls bnder
helmsrkpr calls bnder
ar_rkpr calls helmrkpr
ar_srkpr calls helmsrkpr