Cp_residual_vt – yaeos
Cp_residual_vt Subroutine
MPL
12 statements
Source File
private subroutine Cp_residual_vt(eos, n, V, T, Cp)
Calculate residual heat capacity pressure constant given V and T.
Examples
eos = PengRobinson76(Tc, Pc, w)
n = [1.0_pr, 1.0_pr]
T = 300.0_pr
V = 1.0_pr
call eos%Cp_residual_vt(n, V, T, Cp=Cp)
Type Bound
ArModel
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: eos
Model
real(kind=pr), intent(in) :: n(:)
Moles number vector
real(kind=pr), intent(in) :: V
Volume [L]
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(out) :: Cp
heat capacity P constant [bar L / K]
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: Cv
real(kind=pr), private :: P
real(kind=pr), private :: dPdT
real(kind=pr), private :: dPdV
real(kind=pr), private :: n_t
Call graph
cp_residual_vt calls cv_residual_vt, pressure
cv_residual_vt calls residual_helmholtz
pressure calls residual_helmholtz