create_generalized_isoz_line – yaeos
create_generalized_isoz_line Function
MPL
76 statements
Source File
public function create_generalized_isoz_line(model, nc, np, nstab, kinds_x, kind_w, z, x_l0, w0, betas0, P0, T0, spec_variable, spec_variable_value, ns0, S0, dS0, ws_stab, max_points)
Create a new generalized line. This function initializes a new instance of the GeneralizedLine type.
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
integer, intent(in) :: nc
integer, intent(in) :: np
integer, intent(in) :: nstab
character(len=14), intent(in) :: kinds_x(np)
character(len=14), intent(in) :: kind_w
real(kind=pr), intent(in) :: z(nc)
real(kind=pr), intent(in) :: x_l0(np,nc)
real(kind=pr), intent(in) :: w0(nc)
real(kind=pr), intent(in) :: betas0(np+1)
real(kind=pr), intent(in) :: P0
real(kind=pr), intent(in) :: T0
integer, intent(in) :: spec_variable
real(kind=pr), intent(in) :: spec_variable_value
integer, intent(in) :: ns0
real(kind=pr), intent(in) :: S0
real(kind=pr), intent(in) :: dS0
real(kind=pr), intent(in), optional :: ws_stab(nstab,nc)
integer, intent(in), optional :: max_points
Return Value type(GeneralizedIsoZLine)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: F(nc*np+np+3)
real(kind=pr), public :: S
real(kind=pr), public :: S1
real(kind=pr), public :: X(nc*np+np+3)
real(kind=pr), public :: dFdS(nc*np+np+3)
real(kind=pr), public :: dS
real(kind=pr), public :: dX(nc*np+np+3)
real(kind=pr), public :: dXdS(nc*np+np+3)
real(kind=pr), public :: df(nc*np+np+3,nc*np+np+3)
logical, public :: found_unstability
integer, public :: i
integer, public :: iBetas(np+1)
integer, public :: iP
integer, public :: iT
integer, public :: i_point
integer, public :: iters
integer, public :: l
integer, public :: lb
integer, public :: max_iters = 1000
integer, public :: ns
integer, public :: ns1
type(MPEquilibriumState), public :: point
real(kind=pr), public :: tms(nstab)
integer, public :: ub
character(len=14), public :: w_kind
character(len=14), public :: x_kinds(np)
Call graph
create_generalized_isoz_line calls mpequilibriumstate_from_x, solve_generalized_point, solve_system, tm
solve_generalized_point calls solve_system, pt_f_np
solve_system calls dgesv
tm calls ln_activity_coefficient, lnphi_pt
pt_f_np calls lnphi_pt
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d