critical_point – yaeos
critical_point Function
MPL
82 statements
Source File
public function critical_point(model, z0, zi, spec, S, max_iters, V0, T0, a0, P0)
Uses
yaeos__math
critical_point
Description
Calculates a single critical point of a mixture using a Newton-Raphson method. It is possible to specify different variables to be fixed with the spec argument, the spec_CP variable helps when selecting the specified variable.
Examples
Default behaviour
  cp = critical_point(&
       model, z0, zi, S=0.5_pr, spec=spec_CP%a, max_iters=1000)
Specifiying another variable
The natural variables are a, lnV, lnT and lnP. So it is important to specify the variable in logaritmic scale if that is the case.
  cp = critical_point(model, z0, zi, S=log(200._pr), spec=spec_CP%P, max_iters=1000)
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Equation of state model
real(kind=pr), intent(in) :: z0(:)
Molar fractions of the first fluid
real(kind=pr), intent(in) :: zi(:)
Molar fractions of the second fluid
integer, intent(in) :: spec
Specification [1:"z", 2:"V", 3:"T", 4:"P"]
real(kind=pr), intent(in) :: S
Specification value
integer, intent(in) :: max_iters
Maxiumum number of iterations
real(kind=pr), intent(in), optional :: V0
Initial volume [L/mol].
real(kind=pr), intent(in), optional :: T0
Initial temperature [K].
real(kind=pr), intent(in), optional :: a0
Initial value
real(kind=pr), intent(in), optional :: P0
Initial Pressure [bar]
Return Value type(EquilibriumState)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: F(4)
real(kind=pr), private :: Sin
real(kind=pr), private :: X(4)
real(kind=pr), private :: a
real(kind=pr), private :: dX(4)
real(kind=pr), private :: df(4,4)
integer, private :: i
real(kind=pr), private :: l
integer, private :: nc
integer, private :: ns
real(kind=pr), private :: u(size(z0))
real(kind=pr), private :: u_new(size(z0))
real(kind=pr), private :: z(size(z0))
Call graph
critical_point calls df_critical, f_critical, get_a, lambda1, pressure, set_a, solve_system, volume
df_critical calls f_critical, get_a
f_critical calls get_a, lambda1
lambda1 calls get_a, eigen, lnfug_vt
pressure calls residual_helmholtz
solve_system calls dgesv
volume calls get_v0, newton
newton calls newton_1d
eigen calls dsyev
lnfug_vt calls residual_helmholtz
get_critical_constants calls critical_point
init_pcsaft calls get_critical_constants