critical_line – yaeos
critical_line Function
MPL
169 statements
Source File
public function critical_line(model, a0, z0, zi, ns0, S0, dS0, v0, t0, p0, max_points, maxP, first_point, stability_analysis)
Uses
yaeos__math_continuation
yaeos__equilibria_equilibrium_state
yaeos__math
critical_line
Description
Calculates the critical line between two mixtures using the continuation method. The two mixtures compositions are restricted to the relation between them, by a parameter , which represents the molar fraction of the second fluid with respect to the whole mixture. Avoid compositions with negative values
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Equation of state model
real(kind=pr), intent(in) :: a0
Initial value
real(kind=pr), intent(in) :: z0(:)
Molar fractions of the first fluid
real(kind=pr), intent(in) :: zi(:)
Molar fractions of the second fluid
integer, intent(in) :: ns0
Position of the specification variable
real(kind=pr), intent(in) :: S0
Specified value
real(kind=pr), intent(in) :: dS0
Initial step size
real(kind=pr), intent(in), optional :: v0
Initial volume [L/mol]
real(kind=pr), intent(in), optional :: t0
Initial temperature [K]
real(kind=pr), intent(in), optional :: p0
Initial pressure [bar]
integer, intent(in), optional :: max_points
Maximum number of points
real(kind=pr), intent(in), optional :: maxP
Maximum pressure
type(EquilibriumState), intent(in), optional :: first_point
logical, optional :: stability_analysis
Return Value type(CriticalLine)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: P
real(kind=pr), private :: S
real(kind=pr), private :: T
real(kind=pr), private :: V
real(kind=pr), private :: V_cep
real(kind=pr), private :: X0(4)
real(kind=pr), private, allocatable :: XS(:,:)
Full set of solved points
real(kind=pr), private, allocatable :: XS_i(:)
Full set of solved points
real(kind=pr), private :: a
logical, private :: found_cep
integer, private :: i
real(kind=pr), private :: max_P
integer, private :: nc
integer, private :: npoints
integer, private :: ns
logical, private :: stab_anal
real(kind=pr), private :: u(size(z0))
eigen-vector
real(kind=pr), private :: u_new(size(z0))
eigen-vector
real(kind=pr), private :: y_cep(size(z0))
real(kind=pr), private :: z(size(z0))
Call graph
critical_line calls df, dfds, dx, dxds, f, df_critical, f_critical, get_a, lambda1, look_for_cep, set_a, solve_system, volume
df_critical calls f_critical, get_a
f_critical calls get_a, lambda1
lambda1 calls get_a, eigen, lnfug_vt
look_for_cep calls get_a, set_a, solve_system, df_cep, f_cep, pressure, stability_check
solve_system calls dgesv
volume calls get_v0, newton
newton calls newton_1d
df_cep calls get_a, f_cep
eigen calls dsyev
f_cep calls get_a, lambda1, lnfug_vt
lnfug_vt calls residual_helmholtz
pressure calls residual_helmholtz
stability_check calls volume, lnfug_vt