Cv_residual_pt – yaeos
Cv_residual_pt Subroutine
MPL
11 statements
Source File
private subroutine Cv_residual_pt(eos, n, P, T, root_type, Cv)
Calculate residual heat capacity at constant volume given pressure and temperature.
Examples
eos = PengRobinson76(Tc, Pc, w)
n = [1.0_pr, 1.0_pr]
T = 300.0_pr
P = 1.0_pr
call eos%Cv_residual_pt(&
   n, P, T, root_type="stable", Cv=Cv &
   )
Type Bound
ArModel
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: eos
Model
real(kind=pr), intent(in) :: n(:)
Moles number vector
real(kind=pr), intent(in) :: P
Pressure [bar]
real(kind=pr), intent(in) :: T
Temperature [K]
character(len=*), intent(in) :: root_type
Desired root-type to solve. Options are: ["liquid", "vapor", "stable"]
real(kind=pr), intent(out) :: Cv
Residual heat capacity at constant volume [bar L K^-1]
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: V
Call graph
cv_residual_pt calls cv_residual_vt, volume
cv_residual_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d