d1mix_rkpr – yaeos
d1mix_rkpr Subroutine
MPL
19 statements
Source File
public pure subroutine d1mix_rkpr(n, d1i, D1, dD1i, dD1ij)
RKPR parameter mixing rule.
The RKPR EoS doesn’t have a constant value for each component, so a proper mixing rule should be provided. A linear combination is used.
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: n(:)
real(kind=pr), intent(in) :: d1i(:)
real(kind=pr), intent(out) :: D1
real(kind=pr), intent(out) :: dD1i(:)
real(kind=pr), intent(out) :: dD1ij(:,:)
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
integer, public :: nc
real(kind=pr), public :: totn
Call graph
d1mixhv calls d1mix_rkpr
d1mixhvnrtl calls d1mix_rkpr
d1mixmhv calls d1mix_rkpr
rkpr_d1mix calls d1mix_rkpr
dmixhvnrtl calls d1mixhvnrtl
dmixhv calls d1mixhv