DandTnder – Yaeos
DandTnder Subroutine
MIT
39 statements
Source File
public subroutine DandTnder(ntd, nc, T, rn, D, dDi, dDiT, dDij, dDdT, dDdT2)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ntd
integer, intent(in) :: nc
real(kind=pr), intent(in) :: T
real(kind=pr), intent(in) :: rn(nc)
real(kind=pr), intent(out) :: D
real(kind=pr), intent(out) :: dDi(nc)
real(kind=pr), intent(out) :: dDiT(nc)
real(kind=pr), intent(out) :: dDij(nc,nc)
real(kind=pr), intent(out) :: dDdT
real(kind=pr), intent(out) :: dDdT2
Calls
Called by
Contents
Variables
aij aux aux2 daijdT daijdT2 i j
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: aij(nc,nc)
real(kind=pr), public :: aux
real(kind=pr), public :: aux2
real(kind=pr), public :: daijdT(nc,nc)
real(kind=pr), public :: daijdT2(nc,nc)
integer, public :: i
integer, public :: j
Call graph
dandtnder calls aijtder
aijtder calls atder
helmrkpr calls dandtnder
helmsrkpr calls dandtnder
ar_rkpr calls helmrkpr
ar_srkpr calls helmsrkpr