df_cep – yaeos
df_cep Function
MPL
27 statements
Source File
private function df_cep(model, nc, X, z0, zi, u)
df_critical
Description
Calculates the Jacobian of the critical point function F_critical.
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Equation of state model
integer, intent(in) :: nc
real(kind=pr), intent(in) :: X(nc+4)
Vector of variables
real(kind=pr), intent(in) :: z0(nc)
Molar fractions of the first fluid
real(kind=pr), intent(in) :: zi(nc)
Molar fractions of the second fluid
real(kind=pr), intent(inout) :: u(nc)
Eigen-vector
Return Value real(kind=pr), (nc+4,nc+4)
Jacobian of the critical point function
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: F1(nc+4)
real(kind=pr), private :: F2(nc+4)
real(kind=pr), private :: a
real(kind=pr), private :: dx(nc+4)
real(kind=pr), private :: eps
integer, private :: i
Call graph
df_cep calls f_cep, get_a
f_cep calls get_a, lambda1, lnfug_vt
lambda1 calls get_a, lnfug_vt, eigen
lnfug_vt calls residual_helmholtz
eigen calls dsyev
look_for_cep calls df_cep
critical_line calls look_for_cep