DmixHV – yaeos
DmixHV Subroutine
MPL
36 statements
Source File
private subroutine DmixHV(self, n, V, T, ai, daidt, daidt2, D, dDdV, dDdT, dDdV2, dDdT2, dDi, dDdTV, dDidV, dDidT, dDij)
Uses
yaeos__models_ar_cubic_mixing_base
Type Bound
HV
Arguments
Type Intent Optional Attributes Name
class(HV), intent(in) :: self
real(kind=pr), intent(in) :: n(:)
Moles vector [mol]
real(kind=pr), intent(in) :: V
Volume [L] (unused)
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(in) :: ai(:)
Pure components attractive parameters
real(kind=pr), intent(in) :: daidt(:)
real(kind=pr), intent(in) :: daidt2(:)
real(kind=pr), intent(out) :: D
Mixture attractive parameter
real(kind=pr), intent(out) :: dDdV
real(kind=pr), intent(out) :: dDdT
real(kind=pr), intent(out) :: dDdV2
real(kind=pr), intent(out) :: dDdT2
real(kind=pr), intent(out) :: dDi(:)
real(kind=pr), intent(out) :: dDdTV
real(kind=pr), intent(out) :: dDidV(:)
real(kind=pr), intent(out) :: dDidT(:)
real(kind=pr), intent(out) :: dDij(:,:)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: Ge
real(kind=pr), private :: GeT
real(kind=pr), private :: GeT2
real(kind=pr), private :: GeTn(size(n))
real(kind=pr), private :: Gen(size(n))
real(kind=pr), private :: Gen2(size(n),size(n))
real(kind=pr), private :: L
real(kind=pr), private :: b
real(kind=pr), private :: bi(size(n))
real(kind=pr), private :: d1
real(kind=pr), private :: d1i(size(n))
real(kind=pr), private :: dL(size(n))
real(kind=pr), private :: dL2(size(n),size(n))
real(kind=pr), private :: dbi(size(n))
real(kind=pr), private :: dbij(size(n),size(n))
real(kind=pr), private :: dd1i(size(n))
real(kind=pr), private :: dd1ij(size(n),size(n))
real(kind=pr), private :: del1(size(n))
real(kind=pr), private :: del2(size(n))
integer, private :: i
integer, private :: j
integer, private :: nc
real(kind=pr), private :: totn
Total number of moles
Call graph
dmixhv calls excess_gibbs, bmixhv, d1mixhv, dmixhv, lamdba_hv
bmixhv calls bmix_linear
d1mixhv calls d1mix_rkpr