DmixHVNRTL – yaeos
DmixHVNRTL Subroutine
MPL
48 statements
Source File
private subroutine DmixHVNRTL(self, n, V, T, ai, daidt, daidt2, D, dDdV, dDdT, dDdV2, dDdT2, dDi, dDdTV, dDidV, dDidT, dDij)
Uses
yaeos__models_ar_cubic_mixing_base
yaeos__models_ge_nrtlhv
Type Bound
HV_NRTL
Arguments
Type Intent Optional Attributes Name
class(HV_NRTL), intent(in) :: self
real(kind=pr), intent(in) :: n(:)
Moles vector [mol]
real(kind=pr), intent(in) :: V
Volume [L] (unused)
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(in) :: ai(:)
Pure components attractive parameters
real(kind=pr), intent(in) :: daidt(:)
real(kind=pr), intent(in) :: daidt2(:)
real(kind=pr), intent(out) :: D
Mixture attractive parameter
real(kind=pr), intent(out) :: dDdV
real(kind=pr), intent(out) :: dDdT
real(kind=pr), intent(out) :: dDdV2
real(kind=pr), intent(out) :: dDdT2
real(kind=pr), intent(out) :: dDi(:)
real(kind=pr), intent(out) :: dDdTV
real(kind=pr), intent(out) :: dDidV(:)
real(kind=pr), intent(out) :: dDidT(:)
real(kind=pr), intent(out) :: dDij(:,:)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: B
real(kind=pr), private :: D1
real(kind=pr), private :: Ge
real(kind=pr), private :: GeT
real(kind=pr), private :: GeT2
real(kind=pr), private :: GeTn(size(n))
real(kind=pr), private :: Gen(size(n))
real(kind=pr), private :: Gen2(size(n),size(n))
real(kind=pr), private :: L
real(kind=pr), private :: bi(size(n))
real(kind=pr), private :: dBi(size(n))
real(kind=pr), private :: dBij(size(n),size(n))
real(kind=pr), private :: dD1i(size(n))
real(kind=pr), private :: dD1ij(size(n),size(n))
type(NRTLHV), private :: ge_model
real(kind=pr), private :: gii(size(n))
real(kind=pr), private :: gji(size(n),size(n))
integer, private :: i
integer, private :: j
integer, private :: nc
Call graph
dmixhvnrtl calls bmixhvnrtl, d1mixhvnrtl, dmixhv, excess_gibbs, lamdba_hv
bmixhvnrtl calls bmix_linear
d1mixhvnrtl calls d1mix_rkpr
dmixhv calls lamdba_hv
excess_gibbs calls nrtl_hv_ge, nrtl_hv_tdep_linear