eigen – yaeos
eigen Subroutine
MPL
26 statements
Source File
public subroutine eigen(A, eigenvalues, eigenvectors)
eigen
Description
Calculate the eigenvalues and eigenvectors of a real symmetric matrix A using LAPACK’s dsyev. The eigenvectors are stored in the columns of eigenvectors. The eigenvalues are stored in eigenvalues.
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(inout) :: A(:,:)
real(kind=pr), intent(out) :: eigenvalues(:)
real(kind=pr), intent(out), optional :: eigenvectors(:,:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: Ain(size(A,1),size(A,1))
integer, public :: istat
integer, public :: n
real(kind=pr), public :: work(size(A,1)*10)
Interfaces
interface
subroutine dsyev(JOBZ, UPLO, N, A, lda, W, WORK, LWORK, INFO)
Arguments
Type Intent Optional Attributes Name
character(len=1) :: JOBZ
character(len=1) :: UPLO
integer :: N
double precision :: A(lda,*)
integer :: lda
double precision :: W(*)
double precision :: WORK(*)
integer :: LWORK
integer :: INFO
Call graph
eigen calls dsyev
lambda1 calls eigen
critical_line calls lambda1, f_critical, df_critical, look_for_cep
critical_point calls lambda1, f_critical, df_critical
f_cep calls lambda1
f_critical calls lambda1
df_cep calls f_cep
df_critical calls f_critical
get_critical_constants calls critical_point
look_for_cep calls f_cep, df_cep
init_pcsaft calls get_critical_constants