enthalpy_residual_pt – yaeos
enthalpy_residual_pt Subroutine
MPL
34 statements
Source File
private subroutine enthalpy_residual_pt(eos, n, P, T, root_type, Hr, HrP, HrT, Hrn)
Calculate residual enthalpy given pressure and temperature.
Examples
eos = PengRobinson76(Tc, Pc, w)
n = [1.0_pr, 1.0_pr]
T = 300.0_pr
P = 1.0_pr
call eos%enthalpy_residual_pt(&
   n, P, T, root_type="stable", Hr=Hr, HrP=HrP, HrT=HrT, Hrn=Hrn &
   )
Type Bound
ArModel
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: eos
Model
real(kind=pr), intent(in) :: n(:)
Moles number vector
real(kind=pr), intent(in) :: P
Pressure [bar]
real(kind=pr), intent(in) :: T
Temperature [K]
character(len=*), intent(in) :: root_type
Desired root-type to solve. Options are: ["liquid", "vapor", "stable"]
real(kind=pr), intent(out), optional :: Hr
Residual enthalpy [bar L]
real(kind=pr), intent(out), optional :: HrP
real(kind=pr), intent(out), optional :: HrT
real(kind=pr), intent(out), optional :: Hrn(size(n))
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: HrT_v
real(kind=pr), private :: HrV_v
real(kind=pr), private :: Hr_v
real(kind=pr), private :: Hrn_v(size(n))
real(kind=pr), private :: P_dummy
real(kind=pr), private :: V
real(kind=pr), private :: dPdT
real(kind=pr), private :: dPdV
real(kind=pr), private :: dPdn(size(n))
logical, private :: dT
real(kind=pr), private :: dVdP
real(kind=pr), private :: dVdT
real(kind=pr), private :: dVdn(size(n))
logical, private :: derivs_present
logical, private :: dn
logical, private :: dp
Call graph
enthalpy_residual_pt calls enthalpy_residual_vt, pressure, volume
enthalpy_residual_vt calls residual_helmholtz
pressure calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d