entropy_residual_pt – yaeos
entropy_residual_pt Subroutine
MPL
37 statements
Source File
private subroutine entropy_residual_pt(eos, n, P, T, root_type, Sr, SrP, SrT, Srn)
Calculate residual entropy given pressure and temperature.
Examples
eos = PengRobinson76(Tc, Pc, w)
n = [1.0_pr, 1.0_pr]
T = 300.0_pr
P = 1.0_pr
call eos%entropy_residual_pt(&
   n, P, T, root_type="stable", Sr=Sr, SrP=SrP, SrT=SrT, Srn=Srn &
   )
Type Bound
ArModel
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: eos
Model
real(kind=pr), intent(in) :: n(:)
Moles number vector
real(kind=pr), intent(in) :: P
Pressure [bar]
real(kind=pr), intent(in) :: T
Temperature [K]
character(len=*), intent(in) :: root_type
Desired root-type to solve. Options are: ["liquid", "vapor", "stable"]
real(kind=pr), intent(out), optional :: Sr
Residual entropy [bar L K^-1]
real(kind=pr), intent(out), optional :: SrP
real(kind=pr), intent(out), optional :: SrT
real(kind=pr), intent(out), optional :: Srn(size(n))
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: P_dummy
real(kind=pr), private :: SrT_v
real(kind=pr), private :: SrV_v
real(kind=pr), private :: Sr_v
real(kind=pr), private :: Srn_v(size(n))
real(kind=pr), private :: V
real(kind=pr), private :: Z
real(kind=pr), private :: dPdT
real(kind=pr), private :: dPdV
real(kind=pr), private :: dPdn(size(n))
real(kind=pr), private :: dVdP
real(kind=pr), private :: dVdT
real(kind=pr), private :: dVdn(size(n))
logical, private :: derivs_present
logical, private :: dn
logical, private :: dp
logical, private :: dt
real(kind=pr), private :: nt
Call graph
entropy_residual_pt calls entropy_residual_vt, pressure, volume
entropy_residual_vt calls residual_helmholtz
pressure calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d