entropy_excess – yaeos
entropy_excess Subroutine
MPL
11 statements
Source File
private subroutine entropy_excess(eos, n, P, T, root_type, Se)
Calculate excess entropy given pressure and temperature.
Examples
```fortran ! eos = PengRobinson76(Tc, Pc, w)
n = [1.0_pr, 1.0_pr] ! T = 300.0_pr ! P = 1.0_pr
call eos%entropy_excess(n, P, T, root_type=”stable”, Se=Se) ```
Type Bound
ArModel
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: eos
Model
real(kind=pr), intent(in) :: n(:)
Moles number vector
real(kind=pr), intent(in) :: P
Pressure [bar]
real(kind=pr), intent(in) :: T
Temperature [K]
character(len=*), intent(in) :: root_type
Desired root-type to solve. Options are: ["liquid", "vapor", "stable"]
real(kind=pr), intent(out) :: Se
Excess entropy [bar L K^-1]
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: dlngammadT(size(n))
real(kind=pr), private :: lngamma(size(n))
Call graph
entropy_excess calls ln_activity_coefficient
ln_activity_coefficient calls lnphi_pt
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d