excess_gibbs – yaeos
excess_gibbs Subroutine
MPL
76 statements
Source File
private subroutine excess_gibbs(self, n, t, Ge, GeT, GeT2, Gen, GeTn, Gen2)
Excess Gibbs model generic interface
Type Bound
GeModelTapenade
Arguments
Type Intent Optional Attributes Name
class(GeModelTapenade), intent(in) :: self
real(kind=pr), intent(in) :: n(:)
real(kind=pr), intent(in) :: t
real(kind=pr), intent(out), optional :: Ge
real(kind=pr), intent(out), optional :: GeT
real(kind=pr), intent(out), optional :: GeT2
real(kind=pr), intent(out), optional, dimension(size(n)) :: Gen
real(kind=pr), intent(out), optional, dimension(size(n)) :: GeTn
real(kind=pr), intent(out), optional :: Gen2(size(n),size(n))
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: geb
real(kind=pr), private :: ged
real(kind=pr), private :: ged0
real(kind=pr), private :: gedb
real(kind=pr), private :: gedd
integer, private :: i
real(kind=pr), private :: nb(size(n))
integer, private :: nc
real(kind=pr), private :: nd(size(n))
real(kind=pr), private :: ndb(size(n))
real(kind=pr), private :: tb
real(kind=pr), private :: td
real(kind=pr), private :: td0
real(kind=pr), private :: tdb
Functions
function get_GenT()
Arguments
None
Return Value real(kind=pr), (size(n))
function get_dGedT()
Arguments
None
Return Value real(kind=pr)
function get_dGedT2()
Arguments
None
Return Value real(kind=pr)
Subroutines
subroutine reset_vars()
Arguments
None
Call graph
excess_gibbs calls ge, ge_b, ge_d_b, get_dgedt, get_dgedt2, get_gent, reset_vars