excess_gibbs – yaeos
excess_gibbs Subroutine
MPL
105 statements
Source File
public subroutine excess_gibbs(self, n, t, Ge, GeT, GeT2, Gen, GeTn, Gen2)
Type Bound
GeModelAdiff
Arguments
Type Intent Optional Attributes Name
class(GeModelAdiff), intent(in) :: self
real(kind=pr), intent(in) :: n(:)
real(kind=pr), intent(in) :: t
real(kind=pr), intent(out), optional :: Ge
real(kind=pr), intent(out), optional :: GeT
real(kind=pr), intent(out), optional :: GeT2
real(kind=pr), intent(out), optional, dimension(size(n)) :: Gen
real(kind=pr), intent(out), optional, dimension(size(n)) :: GeTn
real(kind=pr), intent(out), optional :: Gen2(size(n),size(n))
Calls
Variables
Type Visibility Attributes Name Initial
logical, public :: any_deriv
real(kind=pr), public :: dGe(size(n)+1,size(n)+1)
type(hyperdual), public :: d_Ge
type(hyperdual), public :: d_n(size(n))
type(hyperdual), public :: d_t
integer, public :: nc
Subroutines
subroutine get_dgedn()
Arguments
None
subroutine get_dgedn2()
Arguments
None
subroutine get_dgedt()
Arguments
None
subroutine get_dgedt2()
Arguments
None
subroutine get_dgedtn()
Arguments
None
subroutine reset_vars()
Arguments
None
Call graph
excess_gibbs calls Ge, get_dgedn, get_dgedn2, get_dgedt, get_dgedt2, get_dgedtn, reset_vars