F_cep – yaeos
F_cep Function
MPL
37 statements
Source File
private function F_cep(model, nc, X, z0, zi, u)
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Equation of state model
integer, intent(in) :: nc
real(kind=pr), intent(in) :: X(nc+4)
Vector of variables
real(kind=pr), intent(in) :: z0(nc)
Molar fractions of the first fluid
real(kind=pr), intent(in) :: zi(nc)
Molar fractions of the second fluid
real(kind=pr), intent(inout) :: u(nc)
Eigen-vector
Return Value real(kind=pr), (nc+4)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: P
real(kind=pr), private :: Pc
real(kind=pr), private :: Py
real(kind=pr), private :: T
real(kind=pr), private :: V
real(kind=pr), private :: Vc
real(kind=pr), private :: Vy
real(kind=pr), private :: Xcp(nc+4)
real(kind=pr), private :: a
real(kind=pr), private, parameter :: eps = 1e-5_pr
real(kind=pr), private :: lnf_y(nc)
real(kind=pr), private :: lnf_z(nc)
real(kind=pr), private :: u_new(nc)
real(kind=pr), private :: y(nc)
real(kind=pr), private :: z(nc)
Call graph
f_cep calls get_a, lambda1, lnfug_vt
lambda1 calls get_a, lnfug_vt, eigen
lnfug_vt calls residual_helmholtz
eigen calls dsyev
df_cep calls f_cep
look_for_cep calls f_cep, df_cep
critical_line calls look_for_cep