find_hpl – yaeos
find_hpl Function
MPL
41 statements
Source File
public function find_hpl(model, z, T0, P0, max_points)
find_hpl
Description
Find a liquid-liquid phase boundary on the PT plane. At a specified pressure. The procedure consists in looking for the temperature at which the fugacity of a component in the mixture is higher than the fugacity of the same component in a pure phase. This is done for each component in the mixture. The component with the highest temperature is selected as it should be the first one appearing. If all components have a negative difference then the mixture is probably stable at all temperatures.
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Equation of state model
real(kind=pr), intent(in) :: z(:)
Mole fractions
real(kind=pr), intent(in) :: T0
Initial temperature [K]
real(kind=pr), intent(in) :: P0
Search pressure [bar]
integer, intent(in) :: max_points
Return Value type(PTEnvel2)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: P
real(kind=pr), private :: T
real(kind=pr), private :: Ts(size(z))
real(kind=pr), private :: diffs(size(z))
type(EquilibriumState), private :: fr
integer, private :: i
real(kind=pr), private :: lnphi_y(size(z))
real(kind=pr), private :: lnphi_z(size(z))
integer, private :: nc
integer, private :: ncomp
real(kind=pr), private :: y(size(z))
Call graph
find_hpl calls lnphi_pt, pt_envelope_2ph
lnphi_pt calls lnphi_vt, volume
pt_envelope_2ph calls optval, continuation, pt_envelope
optval calls optval_character, optval_integer, optval_real
continuation calls full_newton, solve_system
lnphi_vt calls residual_helmholtz
pt_envelope calls optval, check_critical_jump, detect_critical, get_values_from_x, solve_point, update_specification
volume calls get_v0, newton
newton calls newton_1d
check_critical_jump calls interpol
detect_critical calls interpol
full_newton calls solve_system
solve_point calls get_values_from_x, solve_system, pt_f_np
solve_system calls dgesv
update_specification calls solve_system, near_critical
pt_f_np calls lnphi_pt, dvnvdb, dvnvdlnkl, dvnvdn, dvwdb, dvwdlnkl