find_llcl – yaeos
find_llcl Subroutine
MPL
40 statements
Source File
public subroutine find_llcl(model, z0, zi, P, a, V, T)
find_llcl
Find an initial guess for the critical L-L line of a binary mixture.
Description
Examples
References
[1] M. Cismondi, M.L. Michelsen, Global phase equilibrium calculations: Critical lines, critical end points and liquid–liquid–vapour equilibrium in binary mixtures, The Journal of Supercritical Fluids 39 (2007) 287–295. https://doi.org/10.1016/j.supflu.2006.03.011.
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Thermodynamic model to use
real(kind=pr), intent(in) :: z0(2)
Mole fractions of original fluid
real(kind=pr), intent(in) :: zi(2)
Mole fractions of new fluid
real(kind=pr), intent(in) :: P
Pressure [bar]
real(kind=pr), intent(out) :: a
Mole fraction of new fluid
real(kind=pr), intent(out) :: V
Volume [L/mol]
real(kind=pr), intent(inout) :: T
Temperature [K]
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: as(50)
real(kind=pr), private :: dlnphidn(2,2)
integer, private :: i
real(kind=pr), private :: lambdas(50)
real(kind=pr), private :: lnphi(2)
integer, private :: tries
real(kind=pr), private :: z(2)
Call graph
find_llcl calls lnphi_pt
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d