flash_no_beta_limits – yaeos
flash_no_beta_limits Function
MPL
112 statements
Source File
public function flash_no_beta_limits(model, z, t, beta0, v_spec, p_spec, k0, iters) result(flash)
Uses
yaeos__auxiliar
Flash algorithm using sucessive substitutions.
Available specifications:
TP (with T and P_spec variables)
TV (with T and V_spec variables)
This algorithm assumes that the specified T and P/V correspond to vapor-liquid separation predicted by the provided model (0
Arguments
Type Intent Optional Attributes Name
class(BaseModel), intent(in) :: model
Thermodynamic model
real(kind=pr), intent(in) :: z(:)
Global composition (molar fractions)
real(kind=pr), intent(in) :: t
Temperature [K]
real(kind=pr), intent(in) :: beta0
Initial guess for vapor fraction
real(kind=pr), intent(in), optional :: v_spec
Specified Volume [L/mol]
real(kind=pr), intent(in), optional :: p_spec
Specified Pressure [bar]
real(kind=pr), intent(in), optional :: k0(:)
Initial K factors (y/x)
integer, intent(out), optional :: iters
Number of iterations
Return Value type(EquilibriumState)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public, dimension(size(z)) :: K
real(kind=pr), public :: P
real(kind=pr), public :: V
real(kind=pr), public :: Vx
real(kind=pr), public :: Vy
real(kind=pr), public :: beta
real(kind=pr), public :: bmax
real(kind=pr), public :: bmin
real(kind=pr), public, dimension(size(z)) :: dK
real(kind=pr), public, dimension(size(z)) :: dKold
real(kind=pr), public :: g0
real(kind=pr), public :: g1
real(kind=pr), public, dimension(size(z)) :: lnK
real(kind=pr), public, dimension(size(z)) :: lnKold
real(kind=pr), public, dimension(size(z)) :: lnfug_x
real(kind=pr), public, dimension(size(z)) :: lnfug_y
character(len=2), public :: spec
Flash specification [PT | VT]
real(kind=pr), public, dimension(size(z)) :: x
real(kind=pr), public, dimension(size(z)) :: y
Call graph
flash_no_beta_limits calls ln_activity_coefficient, lnphi_pt, pressure, k_wilson, pressure_equality_v_beta_xy, solve_rr
pressure_equality_v_beta_xy calls get_v0, pressure
solve_rr calls betalimits, rachford_rice
pressure calls residual_helmholtz