flash – Yaeos
flash Function
MPL
110 statements
Source File
public function flash(self, z, t, v_spec, p_spec, k0, iters)
This algorithm assumes that the specified T and P correspond to vapor-liquid separation predicted by the provided model (0<beta<1)
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: self
Thermodynamic model
real(kind=pr), intent(in) :: z(:)
Global composition (molar fractions)
real(kind=pr), intent(in) :: t
Temperature [K]
real(kind=pr), intent(in), optional :: v_spec
Specified Volume [L/mol]
real(kind=pr), intent(in), optional :: p_spec
Specified Pressure [bar]
real(kind=pr), intent(in) :: k0(:)
Initial K factors (y/x)
integer, intent(out), optional :: iters
Number of iterations
Return Value type(EquilibriaState)
Calls
Contents
Variables
DPVl K Vx Vy aux beta bmax bmin bx dK dKold dVydVl dlnphidn dpvv g0 g1 h lnK lnKold lnfug_x lnfug_y log_k2 p pl pold pold2 pv rho_x rho_y savek spec step stepv stopflash told told2 v x y
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: DPVl
real(kind=pr), public, dimension(size(z)) :: K
real(kind=pr), public :: Vx
real(kind=pr), public :: Vy
real(kind=pr), public :: aux
real(kind=pr), public :: beta
real(kind=pr), public :: bmax
real(kind=pr), public :: bmin
real(kind=pr), public :: bx
real(kind=pr), public, dimension(size(z)) :: dK
real(kind=pr), public, dimension(size(z)) :: dKold
real(kind=pr), public :: dVydVl
real(kind=pr), public, dimension(size(z), size(z)) :: dlnphidn
real(kind=pr), public :: dpvv
real(kind=pr), public :: g0
real(kind=pr), public :: g1
real(kind=pr), public :: h
real(kind=pr), public, dimension(size(z)) :: lnK
real(kind=pr), public, dimension(size(z)) :: lnKold
real(kind=pr), public, dimension(size(z)) :: lnfug_x
real(kind=pr), public, dimension(size(z)) :: lnfug_y
real(kind=pr), public :: log_k2(size(z))
real(kind=pr), public :: p
real(kind=pr), public :: pl
real(kind=pr), public :: pold
real(kind=pr), public :: pold2
real(kind=pr), public :: pv
real(kind=pr), public :: rho_x
real(kind=pr), public :: rho_y
real(kind=pr), public :: savek(size(z))
character(len=2), public :: spec
Flash specification [PT | VT]
real(kind=pr), public :: step
real(kind=pr), public :: stepv
logical, public :: stopflash
real(kind=pr), public :: told
real(kind=pr), public :: told2
real(kind=pr), public :: v
real(kind=pr), public, dimension(size(z)) :: x
real(kind=pr), public, dimension(size(z)) :: y
Call graph
flash calls pressure, fugacity_tp, betalimits, solve_rr, betato01
fugacity_tp calls vcalc, fugacity_vt
solve_rr calls betalimits, rachford_rice
vcalc calls optval