fugacity_tp – yaeos
fugacity_tp Subroutine
MPL
17 statements
Source File
public subroutine fugacity_tp(self, n, t, p, v, root_type, lnfug, dlnphidp, dlnphidt, dlnphidn)
Uses
iso_fortran_env
Calculate logarithm of fugacity, given pressure and temperature.
This routine will obtain the desired volume root at the specified pressure and calculate fugacity at that point.
Note
While the natural output variable is . The calculated derivatives will be the derivatives of the fugacity coefficient
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: self
Model
real(kind=pr), intent(in) :: n(:)
Mixture mole numbers
real(kind=pr), intent(in) :: t
Temperature [K]
real(kind=pr), intent(in) :: p
Pressure [bar]
real(kind=pr), intent(out), optional :: v
Volume [L]
character(len=*), intent(in) :: root_type
Type of root desired [“liquid”, “vapor”, “stable”]
real(kind=pr), intent(out) :: lnfug(size(n))
vector
real(kind=pr), intent(out), optional :: dlnphidp(size(n))
ln(phi) Presssure derivative
real(kind=pr), intent(out), optional :: dlnphidt(size(n))
ln(phi) Temp derivative
real(kind=pr), intent(out), optional :: dlnphidn(size(n),size(n))
ln(phi) compositional derivative
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: p_in
real(kind=pr), public :: v_in
Call graph
fugacity_tp calls fugacity_vt, vcalc
fugacity_vt calls residual_helmholtz
vcalc calls get_v0, optval, residual_helmholtz
flash calls fugacity_tp