full_newton – yaeos
full_newton Subroutine
MPL
35 statements
Source File
public subroutine full_newton(fun, iters, X, ns, S, dS, dXdS, point, max_iters, F, df, dfds, tol)
Uses
yaeos__math_linalg
yaeos__auxiliar
Subroutine to solve a point.
Procedure that solves a point with the Newton-Raphson method.
Arguments
Type Intent Optional Attributes Name
procedure(continuation_function) :: fun
Function to solve
integer, intent(out) :: iters
Number of iterations needed
real(kind=pr), intent(inout) :: X(:)
Variables vector
integer, intent(in) :: ns
real(kind=pr), intent(in) :: S
real(kind=pr), intent(in) :: dS
real(kind=pr), intent(in) :: dXdS(:)
integer, intent(in) :: point
integer, intent(in) :: max_iters
Maximum iterations
real(kind=pr), intent(out) :: F(:)
Function values at solved point
real(kind=pr), intent(out) :: df(:,:)
Jacobian values
real(kind=pr), intent(out) :: dfds(:)
dFdS
real(kind=pr), intent(in) :: tol
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: X0(size(X))
real(kind=pr), public :: dX(size(X))
real(kind=pr), public :: solve_tol
Call graph
full_newton calls solve_system
solve_system calls dgesv
continuation calls full_newton
px_envelope_2ph calls continuation
tx_envelope_2ph calls continuation