gerg_2008 – yaeos
gerg_2008 Function
MPL
11 statements
Source File
public function gerg_2008(ids)
Uses
yaeos__models_ar_multifluid_parameters_gerg2008
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ids(:)
Return Value type(Gerg2008)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(Gerg2008Binary), public :: binaries(size(ids),size(ids))
type(Gerg2008Pure), public :: pures(size(ids))
Call graph
gerg_2008 calls get_original_parameters, soaveredlichkwong
get_original_parameters calls original_parameters
ln_activity_coefficient calls gerg_2008