get_subgroups_cij – yaeos
get_subgroups_cij Function
MPL
12 statements
Source File
public function get_subgroups_cij(self, subgroup_i_id, subgroup_j_id) result(cij)
get_subgroups_cij
Get the interaction parameter
Description
Get the interaction parameter of the subgroups i and j ids.
Examples
 use yaeos__models_ge_group_contribution_unifac_parameters, only: UNIFACParameters
 use yaeos__models_ge_group_contribution_model_parameters, only: GeGCModelParameters
 type(GeGCModelParameters) :: parameters
 parameters = UNIFACParameters()
 ! Get the subgroups i:1, j:16 interaction parameter cij (CH3-H2O)
 ! with maingroups 1 and 7 respectively.
 print *, parameters%get_subgroups_cij(1, 16) ! prints: 0.0000
In the example we obtain 0.0 because UNIFAC only have parameters
References
Dortmund Data Bank Software & Separation Technology
Type Bound
GeGCModelParameters
Arguments
Type Intent Optional Attributes Name
class(GeGCModelParameters) :: self
integer, intent(in) :: subgroup_i_id
ID of the subgroup i
integer, intent(in) :: subgroup_j_id
ID of the subgroup j
Return Value real(kind=pr)
Interaction parameter
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
integer, public :: mi_id
integer, public :: mj_id
Call graph
get_subgroups_cij calls get_maingroup_index, get_subgroup_maingroup
get_subgroup_maingroup calls get_subgroup_index
setup_dortmund calls get_subgroups_cij
setup_psrk calls get_subgroups_cij
psrk calls setup_psrk