get_subgroup_index – yaeos
get_subgroup_index Function
MPL
6 statements
Source File
public function get_subgroup_index(self, subgroup_id) result(subgroup_idx)
get_subgroup_index
Get index of the subgroup with id: subgroup_id
Description
Get index of the subgroup with id: subgroup_id. Gets the index of the subgroup in the self%subgroups_ids vector.
Examples
 use yaeos__models_ge_group_contribution_unifac_parameters, only: UNIFACParameters
 use yaeos__models_ge_group_contribution_model_parameters, only: GeGCModelParameters
 type(GeGCModelParameters) :: parameters
 ! Default parameters of UNIFAC (ddbst)
 parameters = UNIFACParameters()
 ! Get index of the subgroup with id 178 (IMIDAZOL)
 print *, parameters%get_subgroup_index(178) ! Will print: 112
References
Dortmund Data Bank Software & Separation Technology
Type Bound
GeGCModelParameters
Arguments
Type Intent Optional Attributes Name
class(GeGCModelParameters) :: self
integer, intent(in) :: subgroup_id
ID of the subgroup
Return Value integer
Index of the subgroup on the self%subgroups_ids vector
Called by
Call graph
get_subgroup_maingroup calls get_subgroup_index
get_subgroup_q calls get_subgroup_index
get_subgroup_r calls get_subgroup_index
get_subgroups_aij calls get_subgroup_maingroup
get_subgroups_bij calls get_subgroup_maingroup
get_subgroups_cij calls get_subgroup_maingroup
setup_unifac calls get_subgroup_q, get_subgroup_r, get_subgroups_aij, thetas_i
thetas_i calls get_subgroup_q
setup_dortmund calls get_subgroups_aij, get_subgroups_bij, get_subgroups_cij, setup_unifac
setup_psrk calls get_subgroups_aij, get_subgroups_bij, get_subgroups_cij, setup_unifac
psrk calls setup_psrk