get_z – yaeos
get_z Subroutine
MPL
9 statements
Source File
public subroutine get_z(alpha, z_0, z_inj, z, dzda)
Calculate the fluid composition based on an amount of addition of second fluid.
The injection can be considered as two kinds of injection: - Displacement: - Addition:
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: alpha
Addition percentaje
real(kind=pr), intent(in) :: z_0(:)
real(kind=pr), intent(in) :: z_inj(:)
real(kind=pr), intent(out) :: z(size(z_0))
New composition
real(kind=pr), intent(out), optional :: dzda(size(z_0))
Derivative wrt
Called by
Call graph
get_values_from_x calls get_z
px_envelope_2ph calls get_z, foo
px_f_np calls get_z
px_f_three_phases calls get_z
tx_envelope_2ph calls get_z, foo
tx_f_np calls get_z
px_envelope calls get_values_from_x, solve_point
px_envelope_3ph calls get_values_from_x, solve_point
solve_point calls tx_f_np, px_f_np, px_f_three_phases
tx_envelope calls get_values_from_x, solve_point