get_subgroup_maingroup – yaeos
get_subgroup_maingroup Function
MPL
8 statements
Source File
public function get_subgroup_maingroup(self, subgroup_id) result(subgroup_maingroup)
get_subgroup_maingroup
Get the subgroup’s maingroup
Description
Uses the self%subgroups_maingroups attribute to locate the maingroup where the subgroup with id subgroup_id belongs
Examples
 use yaeos__models_ge_group_contribution_unifac_parameters, only: UNIFACParameters
 use yaeos__models_ge_group_contribution_model_parameters, only: GeGCModelParameters
 type(GeGCModelParameters) :: parameters
 parameters = UNIFACParameters()
 ! Get the maingroup of the subgroup with id 16 (H2O)
 print *, parameters%get_subgroup_maingroup(16) ! Will print: 7
References
Dortmund Data Bank Software & Separation Technology
Type Bound
GeGCModelParameters
Arguments
Type Intent Optional Attributes Name
class(GeGCModelParameters) :: self
integer, intent(in) :: subgroup_id
ID of the subgroup
Return Value integer
Maingroup of the subgroup
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: subgroup_idx
Call graph
get_subgroup_maingroup calls get_subgroup_index
get_subgroups_aij calls get_subgroup_maingroup
get_subgroups_bij calls get_subgroup_maingroup
get_subgroups_cij calls get_subgroup_maingroup
setup_dortmund calls get_subgroups_aij, get_subgroups_bij, get_subgroups_cij, setup_unifac
setup_psrk calls get_subgroups_aij, get_subgroups_bij, get_subgroups_cij, setup_unifac
setup_unifac calls get_subgroups_aij
psrk calls setup_psrk