get_maingroup_index – yaeos
get_maingroup_index Function
MPL
6 statements
Source File
public function get_maingroup_index(self, maingroup_id) result(maingroup_idx)
get_maingroup_index
Get index of the maingoup with id: maingoup_id
Description
Get index of the maingoup with id: maingoup_id. Gets the index of the maingoup in the self%maingoups_ids vector.
Examples
 use yaeos__models_ge_group_contribution_unifac_parameters, only: UNIFACParameters
 use yaeos__models_ge_group_contribution_model_parameters, only: GeGCModelParameters
 type(GeGCModelParameters) :: parameters
 parameters = UNIFACParameters()
 ! Get index of the maingroup with id 55 (Sulfones: [118](CH2)2SU [119]CH2CHSU)
 print *, parameters%get_maingroup_index(55) ! Will print: 52
References
Dortmund Data Bank Software & Separation Technology
Type Bound
GeGCModelParameters
Arguments
Type Intent Optional Attributes Name
class(GeGCModelParameters) :: self
integer, intent(in) :: maingroup_id
ID of the subgroup
Return Value integer
Index of the maingroup on the self%maingroups_ids vector
Called by
Call graph
get_maingroups_aij calls get_maingroup_index
get_maingroups_bij calls get_maingroup_index
get_maingroups_cij calls get_maingroup_index
get_subgroups_aij calls get_maingroup_index
get_subgroups_bij calls get_maingroup_index
get_subgroups_cij calls get_maingroup_index
setup_dortmund calls get_subgroups_aij, get_subgroups_bij, get_subgroups_cij, setup_unifac
setup_psrk calls get_subgroups_aij, get_subgroups_bij, get_subgroups_cij, setup_unifac
setup_unifac calls get_subgroups_aij
psrk calls setup_psrk