get_Zc_OMa_OMb – yaeos
get_Zc_OMa_OMb Subroutine
MPL
12 statements
Source File
public subroutine get_Zc_OMa_OMb(del1, Zc, OMa, OMb)
Calculate Zc, OMa and OMb from the delta_1 parameter.
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: del1(:)
delta_1 parameter
real(kind=pr), intent(out) :: Zc(:)
Critical compressibility factor
real(kind=pr), intent(out) :: OMa(:)
OMa
real(kind=pr), intent(out) :: OMb(:)
OMb
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: d1(size(del1))
real(kind=pr), public :: y(size(del1))
Call graph
pr76_factory calls get_zc_oma_omb
pr78_factory calls get_zc_oma_omb
srk_factory calls get_zc_oma_omb