get_values_from_X – yaeos
get_values_from_X Subroutine
MPL
28 statements
Source File
private subroutine get_values_from_X(X, np, z, beta_w, x_l, w, betas, P, T)
get_values_from_X
Extract the values of the variables from the vector X.
Type Bound
PTEnvelMP
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: X(:)
Vector of variables.
integer, intent(in) :: np
Number of main phases.
real(kind=pr), intent(in) :: z(:)
Mixture composition.
real(kind=pr), intent(in) :: beta_w
Fraction of the reference phase.
real(kind=pr), intent(out) :: x_l(np,size(z))
Mole fractions of the main phases.
real(kind=pr), intent(out) :: w(size(z))
Mole fractions of the incipient phase.
real(kind=pr), intent(out) :: betas(np)
Fractions of the main phases.
real(kind=pr), intent(out) :: P
Pressure [bar].
real(kind=pr), intent(out) :: T
Temperature [K].
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
Loop index.
integer, private :: lb
Lower bound of each phase.
integer, private :: nc
Number of components.
integer, private :: ub
Upper bound of each phase.
Call graph
pt_envelope calls get_values_from_x, solve_point
solve_point calls get_values_from_x
pt_envelope_2ph calls pt_envelope
find_hpl calls pt_envelope_2ph