get_critical_constants – yaeos
get_critical_constants Subroutine
MPL
16 statements
Source File
public subroutine get_critical_constants(model)
get_critical_constants
Calculate the critical constants for each pure component.
Description
Calculates the critical temperature, pressure and acentric factor for each pure component in the model. The critical points are calculated using the critical_point function from the yaeos__equilibria_critical module. The acentric factor is calculated using the saturation pressure at 0.7 of the critical temperature. It updates the Tc, Pc and w attributes of each component in the model.
Note
This subroutine assumes that the pure component constants for each component are already allocated.
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(inout) :: model
Thermodynamic model.
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: Psat_i
type(EquilibriumState), private :: cp
integer, private :: i
integer, private :: nc
real(kind=pr), private :: z(size(model%components%Tc))
Call graph
get_critical_constants calls critical_point, psat_pure
critical_point calls df_critical, f_critical, get_a, lambda1, pressure, set_a, solve_system, volume
psat_pure calls pressure, solve_point_psat, volume
df_critical calls f_critical, get_a
f_critical calls get_a, lambda1
lambda1 calls get_a, eigen, lnfug_vt
pressure calls residual_helmholtz
solve_point_psat calls solve_system, get_v0, isofugacity
solve_system calls dgesv
volume calls get_v0, newton
newton calls newton_1d
eigen calls dsyev
lnfug_vt calls residual_helmholtz
init_pcsaft calls get_critical_constants