get_a – yaeos
get_a Function
MPL
9 statements
Source File
private function get_a(nc, X)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nc
real(kind=pr), intent(in) :: X
Return Value real(kind=pr)
Called by
Call graph
critical_line calls get_a, df_critical, f_critical, lambda1, look_for_cep
critical_point calls get_a, df_critical, f_critical, lambda1
df_cep calls get_a, f_cep
df_critical calls get_a, f_critical
f_cep calls get_a, lambda1
f_critical calls get_a, lambda1
lambda1 calls get_a
look_for_cep calls get_a, df_cep, f_cep
get_critical_constants calls critical_point
init_pcsaft calls get_critical_constants