HelmSRKPR – Yaeos
HelmSRKPR Subroutine
MPL
62 statements
Source File
public subroutine HelmSRKPR(nc, nd, nt, rn, v, t, ar, arv, artv, arv2, Arn, ArVn, ArTn, Arn2)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nc
Number of components
integer, intent(in) :: nd
Compositional derivatives
integer, intent(in) :: nt
Temperature derivatives
real(kind=pr), intent(in) :: rn(nc)
Number of moles
real(kind=pr), intent(in) :: v
Volume [L]
real(kind=pr), intent(in) :: t
Temperature [K]
real(kind=pr), intent(out) :: ar
Residual Helmholtz
real(kind=pr), intent(out) :: arv
dAr/dV
real(kind=pr), intent(out) :: artv
dAr2/dTV
real(kind=pr), intent(out) :: arv2
dAr2/dV2
real(kind=pr), intent(out) :: Arn(nc)
dAr/dn
real(kind=pr), intent(out) :: ArVn(nc)
dAr2/dVn
real(kind=pr), intent(out) :: ArTn(nc)
dAr2/dTn
real(kind=pr), intent(out) :: Arn2(nc,nc)
dAr2/dn2
Calls
Called by
Contents
Variables
AUX ArT ArTT Bmix D FFB FFBB FFBV a b_v d1 d2 dBi dBij dDdT dDdT2 dDi dDiT dDij f fB fv fv2 g gv gv2 i j totn
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: AUX
real(kind=pr), public :: ArT
real(kind=pr), public :: ArTT
real(kind=pr), public :: Bmix
real(kind=pr), public :: D
real(kind=pr), public :: FFB
real(kind=pr), public :: FFBB
real(kind=pr), public :: FFBV
real(kind=pr), public :: a
real(kind=pr), public :: b_v
real(kind=pr), public :: d1
real(kind=pr), public :: d2
real(kind=pr), public :: dBi(nc)
real(kind=pr), public :: dBij(nc,nc)
real(kind=pr), public :: dDdT
real(kind=pr), public :: dDdT2
real(kind=pr), public :: dDi(nc)
real(kind=pr), public :: dDiT(nc)
real(kind=pr), public :: dDij(nc,nc)
real(kind=pr), public :: f
real(kind=pr), public :: fB
real(kind=pr), public :: fv
real(kind=pr), public :: fv2
real(kind=pr), public :: g
real(kind=pr), public :: gv
real(kind=pr), public :: gv2
integer, public :: i
integer, public :: j
real(kind=pr), public :: totn
Call graph
helmsrkpr calls bnder, dandtnder
dandtnder calls aijtder
aijtder calls atder
ar_srkpr calls helmsrkpr