HelmRKPR – yaeos
HelmRKPR Subroutine
MPL
68 statements
Source File
public subroutine HelmRKPR(nco, NDE, NTD, rn, V, T, Ar, ArV, ArTV, ArV2, Arn, ArVn, ArTn, Arn2)
Calculate the reduced residual Helmholtz Energy and it’s derivatives with the RKPR EOS
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nco
integer, intent(in) :: NDE
integer, intent(in) :: NTD
real(kind=pr), intent(in) :: rn(nco)
real(kind=pr), intent(in) :: V
real(kind=pr), intent(in) :: T
real(kind=pr), intent(out) :: Ar
real(kind=pr), intent(out) :: ArV
real(kind=pr), intent(out) :: ArTV
real(kind=pr), intent(out) :: ArV2
real(kind=pr), intent(out) :: Arn(nco)
real(kind=pr), intent(out) :: ArVn(nco)
real(kind=pr), intent(out) :: ArTn(nco)
real(kind=pr), intent(out) :: Arn2(nco,nco)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: AUX
real(kind=pr), public :: ArT
real(kind=pr), public :: ArTT
real(kind=pr), public :: Bmix
real(kind=pr), public :: D
real(kind=pr), public :: D1
real(kind=pr), public :: D2
real(kind=pr), public :: FFB
real(kind=pr), public :: FFBB
real(kind=pr), public :: FFBV
real(kind=pr), public :: auxD2
real(kind=pr), public :: dBi(nco)
real(kind=pr), public :: dBij(nco,nco)
real(kind=pr), public :: dD1i(nco)
real(kind=pr), public :: dD1ij(nco,nco)
real(kind=pr), public :: dDdT
real(kind=pr), public :: dDdT2
real(kind=pr), public :: dDi(nco)
real(kind=pr), public :: dDiT(nco)
real(kind=pr), public :: dDij(nco,nco)
real(kind=pr), public :: f
real(kind=pr), public :: fB
real(kind=pr), public :: fBD1
real(kind=pr), public :: fD1
real(kind=pr), public :: fD1D1
real(kind=pr), public :: fVD1
real(kind=pr), public :: fv
real(kind=pr), public :: fv2
real(kind=pr), public :: g
real(kind=pr), public :: gv
real(kind=pr), public :: gv2
integer, public :: i
integer, public :: j
real(kind=pr), public :: totn
Call graph
helmrkpr calls bnder, dandtnder, deltander
dandtnder calls aijtder
aijtder calls atder
ar_rkpr calls helmrkpr