homotopy – yaeos
homotopy Subroutine
MPL
49 statements
Source File
public subroutine homotopy(sub, x, tol, max_its, its)
Uses
yaeos__math
Arguments
Type Intent Optional Attributes Name
procedure(to_solve) :: sub
real(kind=pr), intent(inout) :: x(:)
real(kind=pr), intent(in) :: tol
integer, intent(in) :: max_its
integer, intent(out) :: its
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: F(size(X))
real(kind=pr), public :: G(size(X))
real(kind=pr), public :: H(size(X))
real(kind=pr), public :: X0(size(X))
real(kind=pr), public :: dF(size(X),size(X))
real(kind=pr), public :: dG(size(X),size(X))
real(kind=pr), public :: dH(size(X),size(X))
real(kind=pr), public :: dX(size(x))
real(kind=pr), public :: dt
integer, public :: i
integer, public :: info
integer, public :: nt
real(kind=pr), public :: t
Subroutines
subroutine fun(n, x, fvec, iflag)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=pr), intent(in) :: x(n)
real(kind=pr), intent(out) :: fvec(n)
integer, intent(inout) :: iflag
subroutine wrap(X, H, dH)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: X(:)
real(kind=pr), intent(out) :: H(:)
real(kind=pr), intent(out) :: dH(:,:)
Call graph
homotopy calls wrap, newton
newton calls solve_system
solve_system calls dgesv