init_pcsaft – yaeos
init_pcsaft Function
MPL
19 statements
Source File
public function init_pcsaft(m, sigma, epsilon_k, kij) result(model)
Uses
yaeos__equilibria_critical
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: m(:)
real(kind=pr), intent(in) :: sigma(:)
real(kind=pr), intent(in) :: epsilon_k(:)
real(kind=pr), intent(in), optional :: kij(:,:)
Return Value type(PcSaft)
Calls
Variables
Type Visibility Attributes Name Initial
integer, private :: nc
Call graph
init_pcsaft calls get_critical_constants
get_critical_constants calls critical_point, psat_pure
critical_point calls df_critical, f_critical, get_a, lambda1, pressure, set_a, solve_system, volume
psat_pure calls pressure, solve_point_psat, volume
df_critical calls f_critical, get_a
f_critical calls get_a, lambda1
lambda1 calls get_a, eigen, lnfug_vt
pressure calls residual_helmholtz
solve_point_psat calls solve_system, get_v0, isofugacity
solve_system calls dgesv
volume calls get_v0, newton
newton calls newton_1d
eigen calls dsyev
lnfug_vt calls residual_helmholtz