internal_energy_excess – yaeos
internal_energy_excess Subroutine
MPL
11 statements
Source File
private subroutine internal_energy_excess(eos, n, P, T, root_type, Ue)
Calculate excess internal energy given pressure and temperature.
Examples
eos = PengRobinson76(Tc, Pc, w)
n = [1.0_pr, 1.0_pr]
T = 300.0_pr
P = 1.0_pr
call eos%internal_energy_excess(n, P, T, root_type="stable", Ue=Ue)
Type Bound
ArModel
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: eos
Model
real(kind=pr), intent(in) :: n(:)
Moles number vector
real(kind=pr), intent(in) :: P
Pressure [bar]
real(kind=pr), intent(in) :: T
Temperature [K]
character(len=*), intent(in) :: root_type
Desired root-type to solve. Options are: ["liquid", "vapor", "stable"]
real(kind=pr), intent(out) :: Ue
Excess internal energy [bar L]
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: dlngammadP(size(n))
real(kind=pr), private :: dlngammadT(size(n))
Call graph
internal_energy_excess calls ln_activity_coefficient
ln_activity_coefficient calls lnphi_pt
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d