k_wilson – yaeos
k_wilson Function
MPL
7 statements
Source File
public function k_wilson(model, T, P) result(K)
K_wilson
Description
K-factors regression done by Wilson, used for initialization.
Arguments
Type Intent Optional Attributes Name
class(BaseModel), intent(in) :: model
real(kind=pr), intent(in) :: T
real(kind=pr), intent(in) :: P
Return Value real(kind=pr), (size(model%components%pc))
Called by
Call graph
flash calls k_wilson
flash_no_beta_limits calls k_wilson
saturation_pressure calls k_wilson
saturation_temperature calls k_wilson