lambda1 – yaeos
lambda1 Function
MPL
36 statements
Source File
public function lambda1(model, X, s, z0, zi, u, u_new, P)
Uses
yaeos__math_linalg
lambda1
Calculation of the first restriction of a critical point.
is the smallest eigen-value for the matrix:
Where And should be the eigen-vector corresponding to the smallest eigen-value when
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
real(kind=pr), intent(in) :: X(4)
Vector of variables
real(kind=pr), intent(in) :: s
Distance between the two fluids compositions to the main composition
real(kind=pr), intent(in) :: z0(:)
Molar fractions of the first fluid
real(kind=pr), intent(in) :: zi(:)
Molar fractions of the second fluid
real(kind=pr), intent(in) :: u(:)
Eigen-vector that defines the direction between the two compositions
real(kind=pr), intent(out), optional :: u_new(:)
Eigen-vector corresponding to the smallest eigenvalue of the matrix
real(kind=pr), intent(out), optional :: P
Pressure of the system [bar]
Return Value real(kind=pr)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: M(size(z0),size(z0))
real(kind=pr), private :: Pin
real(kind=pr), private :: T
real(kind=pr), private :: V
real(kind=pr), private :: a
real(kind=pr), private :: dlnf_dn(size(z0),size(z0))
integer, private :: i
integer, private :: j
real(kind=pr), private :: lambda(size(z0))
real(kind=pr), private :: n(size(z0))
integer, private :: nc
real(kind=pr), private :: vectors(size(z0),size(z0))
real(kind=pr), private :: z(size(z0))
Call graph
lambda1 calls eigen, get_a, lnfug_vt
eigen calls dsyev
lnfug_vt calls residual_helmholtz
critical_line calls lambda1, f_critical, df_critical, look_for_cep
critical_point calls lambda1, f_critical, df_critical
f_cep calls lambda1
f_critical calls lambda1
df_cep calls f_cep
df_critical calls f_critical
get_critical_constants calls critical_point
look_for_cep calls f_cep, df_cep
init_pcsaft calls get_critical_constants