lamdba_hv – yaeos
lamdba_hv Subroutine
MPL
30 statements
Source File
public subroutine lamdba_hv(nc, d1, dd1i, dd1ij, L, dLi, dLij)
Infinite pressure limit parameter
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nc
real(kind=pr), intent(in) :: d1
real(kind=pr), intent(in), optional :: dd1i(nc)
real(kind=pr), intent(in), optional :: dd1ij(nc,nc)
real(kind=pr), intent(out) :: L
real(kind=pr), intent(out), optional :: dLi(nc)
real(kind=pr), intent(out), optional :: dLij(nc,nc)
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public, dimension(nc, nc) :: d2f
real(kind=pr), public, dimension(nc, nc) :: d2g
real(kind=pr), public, dimension(nc, nc) :: d2h
real(kind=pr), public, dimension(nc) :: df
real(kind=pr), public, dimension(nc) :: dg
real(kind=pr), public, dimension(nc) :: dh
real(kind=pr), public :: f
real(kind=pr), public :: g
real(kind=pr), public :: h
integer, public :: i
integer, public :: j
Call graph
dmixhv calls lamdba_hv, dmixhv
dmixhvnrtl calls lamdba_hv, dmixhv