ln_activity_coefficient – yaeos
ln_activity_coefficient Subroutine
MPL
53 statements
Source File
public subroutine ln_activity_coefficient(eos, n, P, T, root_type, lngamma, dlngammadP, dlngammadT, dlngammadn)
Calculate natural logarithm of activity coefficients and its derivatives given pressure and temperature.
Examples
```fortran ! eos = PengRobinson76(Tc, Pc, w)
n = [1.0_pr, 1.0_pr] ! T = 300.0_pr ! P = 1.0_pr
call eos%ln_activity_coefficient(& n, P, T, root_type=”stable”, & lngamma=lngamma, dlngammadP=dlngammadP, & dlngammadT=dlngammadT, dlngammadn=dlngammadn &) ```
Type Bound
Gerg2008
Arguments
Type Intent Optional Attributes Name
class(Gerg2008), intent(in) :: eos
Model
real(kind=pr), intent(in) :: n(:)
Moles number vector
real(kind=pr), intent(in) :: P
Pressure [bar]
real(kind=pr), intent(in) :: T
Temperature [K]
character(len=*), intent(in) :: root_type
Desired root-type to solve. Options are: ["liquid", "vapor", "stable"]
real(kind=pr), intent(out), optional :: lngamma(size(n))
Natural logarithm of activity coefficient
real(kind=pr), intent(out), optional :: dlngammadP(size(n))
real(kind=pr), intent(out), optional :: dlngammadT(size(n))
real(kind=pr), intent(out), optional :: dlngammadn(size(n),size(n))
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: dPdV
real(kind=pr), public :: dPdn(size(n))
real(kind=pr), public :: dVdn(size(n))
real(kind=pr), public :: dlnPhi_i_dT(size(n))
real(kind=pr), public :: dlnPhi_i_dT_temp(1)
real(kind=pr), public :: dlnPhidT(size(n))
real(kind=pr), public :: dlnPhidn(size(n),size(n))
logical, public :: dn
logical, public :: dp
logical, public :: dt
type(Gerg2008), public :: eos_temp
logical, public :: gam
integer, public :: i
real(kind=pr), public :: lnPhi(size(n))
real(kind=pr), public :: lnPhi_i(size(n))
real(kind=pr), public :: lnPhi_i_temp(1)
real(kind=pr), public :: npure(size(n))
logical, public :: present_derivs
real(kind=pr), public :: vi(size(n))
real(kind=pr), public :: vi_temp
Call graph
ln_activity_coefficient calls gerg_2008, lnphi_pt
gerg_2008 calls get_original_parameters, soaveredlichkwong
lnphi_pt calls lnphi_vt, volume
get_original_parameters calls original_parameters
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d