ln_phi – Yaeos
ln_phi Subroutine
MIT
12 statements
Source File
public subroutine ln_phi(z, v, t, lnphi)
Fugacity coefficent as a function of volume and temperature. The fugacity coefficent is the first derivative of the Residual Helmholtz energy, substracted with the compressibility factor:
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: z(:)
Composition vector
real(kind=pr), intent(in) :: v
Volume
real(kind=pr), intent(in) :: t
Temperature
real(kind=pr), intent(out) :: lnphi(size(z))
Fugacity coefficent
Calls
Contents
Variables
ar compressibility dar dar2 p
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: ar
real(kind=pr), private :: compressibility
real(kind=pr), private :: dar(size(z)+2)
real(kind=pr), private :: dar2(size(z)+2,size(z)+2)
real(kind=pr), private :: p
Call graph
ln_phi calls pressure, residual_helmholtz
pressure calls residual_helmholtz
residual_helmholtz calls dualderiv