lnfug_vt – yaeos
lnfug_vt Subroutine
MPL
68 statements
Source File
private subroutine lnfug_vt(eos, n, V, T, P, lnf, dlnfdV, dlnfdT, dlnfdn, dPdV, dPdT, dPdn)
Calculate natural logarithm of fugacity given volume and temperature.
Calculate the natural logarithm of the fugacity and its derivatives. The routine gives the possibility to calculate the pressure and it’s derivatives.
Examples
eos = PengRobinson76(Tc, Pc, w)
n = [1.0_pr, 1.0_pr]
T = 300.0_pr
V = 1.0_pr
call eos%lnfug_vt(&
   n, V, T, lnf=lnf, &
   dlnfdV=dlnfdV, dlnfdT=dlnfdT, dlnfdn=dlnfdn &
   )
Type Bound
ArModel
Arguments
Type Intent Optional Attributes Name
class(ArModel) :: eos
Model
real(kind=pr), intent(in) :: n(:)
Mixture mole numbers
real(kind=pr), intent(in) :: V
Volume [L]
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(out), optional :: P
Pressure [bar]
real(kind=pr), intent(out), optional :: lnf(size(n))
vector
real(kind=pr), intent(out), optional :: dlnfdV(size(n))
Volume derivative
real(kind=pr), intent(out), optional :: dlnfdT(size(n))
Temp derivative
real(kind=pr), intent(out), optional :: dlnfdn(size(n),size(n))
compositional derivative
real(kind=pr), intent(out), optional :: dPdV
real(kind=pr), intent(out), optional :: dPdT
real(kind=pr), intent(out), optional :: dPdn(:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: Ar
real(kind=pr), private :: ArTV
real(kind=pr), private, dimension(size(n)) :: ArTn
real(kind=pr), private :: ArV
real(kind=pr), private :: ArV2
real(kind=pr), private, dimension(size(n)) :: ArVn
real(kind=pr), private, dimension(size(n)) :: Arn
real(kind=pr), private :: Arn2(size(n),size(n))
real(kind=pr), private :: P_in
real(kind=pr), private :: RT
real(kind=pr), private :: Z
real(kind=pr), private :: dPdT_in
real(kind=pr), private :: dPdV_in
real(kind=pr), private :: dPdn_in(size(n))
integer, private :: i
integer, private :: j
integer, private :: nc
real(kind=pr), private :: totn
Call graph
lnfug_vt calls residual_helmholtz
f_cep calls lnfug_vt, lambda1
lambda1 calls lnfug_vt
saturation_f calls lnfug_vt
stability_check calls lnfug_vt
three_phase_line_f calls lnfug_vt
critical_line calls lambda1, f_critical, look_for_cep, df_critical
critical_point calls lambda1, f_critical, df_critical
df_cep calls f_cep
f_critical calls lambda1
look_for_cep calls f_cep, stability_check, df_cep
solve_point_psat calls isofugacity
solve_point calls isofugacity
solve_vxvyt calls saturation_f
three_phase_line_f_solve calls three_phase_line_f
binary_llv_from_cep calls three_phase_line_f_solve
df_critical calls f_critical
get_critical_constants calls critical_point, psat_pure
psat_pure calls solve_point_psat
pure_saturation_line calls solve_point
init_pcsaft calls get_critical_constants
refit_rkpr_k calls psat_pure, pure_saturation_line
rkpr calls refit_rkpr_k