lnphi_pt – yaeos
lnphi_pt Subroutine
MPL
21 statements
Source File
private subroutine lnphi_pt(eos, n, P, T, V, root_type, lnPhi, dlnPhidP, dlnPhidT, dlnPhidn, dPdV, dPdT, dPdn, lnPhiP)
Uses
iso_fortran_env
Calculate natural logarithm of fugacity given pressure and temperature.
Calculate the natural logarithm of the fugacity coefficient and its derivatives given pressure and temperature. This routine will obtain the desired volume root at the specified pressure and calculate fugacity at that point.The routine gives the possibility to calculate the pressure derivatives and volume.
Examples
eos = PengRobinson76(Tc, Pc, w)
n = [1.0_pr, 1.0_pr]
T = 300.0_pr
V = 1.0_pr
call eos%lnphi_pt(&
   n, V, T, lnPhi=lnPhi, &
   dlnPhidP=dlnPhidP, dlnPhidT=dlnPhidT, dlnPhidn=dlnPhidn &
   )
Type Bound
ArModel
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: eos
Model
real(kind=pr), intent(in) :: n(:)
Mixture mole numbers
real(kind=pr), intent(in) :: P
Pressure [bar]
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(out), optional :: V
Volume [L]
character(len=*), intent(in) :: root_type
Type of root desired [“liquid”, “vapor”, “stable”]
real(kind=pr), intent(out), optional :: lnPhi(size(n))
vector
real(kind=pr), intent(out), optional :: dlnPhidP(size(n))
ln(phi) Presssure derivative
real(kind=pr), intent(out), optional :: dlnPhidT(size(n))
ln(phi) Temperature derivative
real(kind=pr), intent(out), optional :: dlnPhidn(size(n),size(n))
ln(phi) compositional derivative
real(kind=pr), intent(out), optional :: dPdV
real(kind=pr), intent(out), optional :: dPdT
real(kind=pr), intent(out), optional :: dPdn(size(n))
real(kind=pr), intent(out), optional :: lnPhiP(:)
. It is useful to calculate fugacity coefficients at negatives pressures.
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: P_in
real(kind=pr), private :: V_in
Call graph
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d
find_hpl calls lnphi_pt, pt_envelope_2ph
find_llcl calls lnphi_pt
ln_activity_coefficient calls lnphi_pt
pt_f_np calls lnphi_pt
pt_f_three_phases calls lnphi_pt
px_f_np calls lnphi_pt
px_f_three_phases calls lnphi_pt
saturation_pressure calls lnphi_pt, solve_tp
saturation_temperature calls lnphi_pt, solve_tp
saturation_tp calls lnphi_pt
tx_f_np calls lnphi_pt
enthalpy_excess calls ln_activity_coefficient
entropy_excess calls ln_activity_coefficient
gibbs_excess calls ln_activity_coefficient
helmholtz_excess calls ln_activity_coefficient
internal_energy_excess calls ln_activity_coefficient
px_envelope_2ph calls foo
solve_generalized_point calls pt_f_np
solve_mp_flash_point calls pt_f_np
solve_point calls tx_f_np, pt_f_three_phases, pt_f_np, px_f_np, px_f_three_phases
tx_envelope_2ph calls foo
volume_excess calls ln_activity_coefficient
create_generalized_isoz_line calls solve_generalized_point
pt_envelope calls solve_point
pt_envelope_3ph calls solve_point
pt_mp_flash calls solve_mp_flash_point
px_envelope calls solve_point
px_envelope_3ph calls solve_point
solve_tp calls wrap
tx_envelope calls solve_point
pt_envelope_2ph calls pt_envelope