lnphi_vt – yaeos
lnphi_vt Subroutine
MPL
72 statements
Source File
private subroutine lnphi_vt(eos, n, V, T, P, lnPhi, dlnPhidP, dlnPhidT, dlnPhidn, dPdV, dPdT, dPdn, lnPhiP)
Calculate natural logarithm of fugacity coefficent.
Calculate the natural logarithm of the fugacity coefficient and its derivatives given volume and temperature. The routine gives the possibility to calculate the pressure and it’s derivatives.
Examples
eos = PengRobinson76(Tc, Pc, w)
n = [1.0_pr, 1.0_pr]
T = 300.0_pr
V = 1.0_pr
call eos%lnphi_vt(&
   n, V, T, lnPhi=lnPhi, &
   dlnPhidP=dlnPhidP, dlnPhidT=dlnPhidT, dlnPhidn=dlnPhidn &
   )
Type Bound
ArModel
Arguments
Type Intent Optional Attributes Name
class(ArModel) :: eos
Model
real(kind=pr), intent(in) :: n(:)
Mixture mole numbers
real(kind=pr), intent(in) :: V
Volume [L]
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(out), optional :: P
Pressure [bar]
real(kind=pr), intent(out), optional :: lnPhi(size(n))
vector
real(kind=pr), intent(out), optional :: dlnPhidP(size(n))
Presssure derivative
real(kind=pr), intent(out), optional :: dlnPhidT(size(n))
Temp derivative
real(kind=pr), intent(out), optional :: dlnPhidn(size(n),size(n))
compositional derivative
real(kind=pr), intent(out), optional :: dPdV
real(kind=pr), intent(out), optional :: dPdT
real(kind=pr), intent(out), optional :: dPdn(:)
real(kind=pr), intent(out), optional :: lnPhiP(:)
. It is useful to calculate fugacity coefficients at negatives pressures.
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: Ar
real(kind=pr), private :: ArTV
real(kind=pr), private, dimension(size(n)) :: ArTn
real(kind=pr), private :: ArV
real(kind=pr), private :: ArV2
real(kind=pr), private, dimension(size(n)) :: ArVn
real(kind=pr), private, dimension(size(n)) :: Arn
real(kind=pr), private :: Arn2(size(n),size(n))
real(kind=pr), private :: P_in
real(kind=pr), private :: RT
real(kind=pr), private :: Z
real(kind=pr), private :: Z_P
real(kind=pr), private :: dPdT_in
real(kind=pr), private :: dPdV_in
real(kind=pr), private :: dPdn_in(size(n))
integer, private :: i
integer, private :: j
integer, private :: nc
real(kind=pr), private :: totn
Call graph
lnphi_vt calls residual_helmholtz
ar_consistency calls lnphi_vt
lnphi_pt calls lnphi_vt
find_hpl calls lnphi_pt, pt_envelope_2ph
find_llcl calls lnphi_pt
ln_activity_coefficient calls lnphi_pt
pt_f_np calls lnphi_pt
pt_f_three_phases calls lnphi_pt
px_f_np calls lnphi_pt
px_f_three_phases calls lnphi_pt
saturation_pressure calls lnphi_pt, solve_tp
saturation_temperature calls lnphi_pt, solve_tp
saturation_tp calls lnphi_pt
tx_f_np calls lnphi_pt
enthalpy_excess calls ln_activity_coefficient
entropy_excess calls ln_activity_coefficient
gibbs_excess calls ln_activity_coefficient
helmholtz_excess calls ln_activity_coefficient
internal_energy_excess calls ln_activity_coefficient
px_envelope_2ph calls foo
solve_generalized_point calls pt_f_np
solve_mp_flash_point calls pt_f_np
solve_point calls px_f_np, px_f_three_phases, pt_f_three_phases, tx_f_np, pt_f_np
tx_envelope_2ph calls foo
volume_excess calls ln_activity_coefficient
create_generalized_isoz_line calls solve_generalized_point
pt_envelope calls solve_point
pt_envelope_3ph calls solve_point
pt_mp_flash calls solve_mp_flash_point
px_envelope calls solve_point
px_envelope_3ph calls solve_point
solve_tp calls wrap
tx_envelope calls solve_point
pt_envelope_2ph calls pt_envelope