logHyperDual – yaeos
logHyperDual Function
MPL
11 statements
Source File
public elemental function logHyperDual(v1) result(v2)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: v1
Return Value type(hyperdual)
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: dx1
real(kind=pr), public :: dx2
Call graph
log calls loghyperdual
powerhyperdualhyperdual calls loghyperdual
operator (ASTERISKASTERISK) calls powerhyperdualhyperdual