look_for_cep – yaeos
look_for_cep Subroutine
MPL
62 statements
Source File
private subroutine look_for_cep(model, z0, zi, Pc, Vc, Tc, a, u, found, CEP)
Uses
yaeos__math
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Equation of state model
real(kind=pr), intent(in) :: z0(:)
Molar fractions of the first fluid
real(kind=pr), intent(in) :: zi(:)
Molar fractions of the second fluid
real(kind=pr), intent(in) :: Pc
Pressure [bar]
real(kind=pr), intent(in) :: Vc
Volume [L/mol]
real(kind=pr), intent(in) :: Tc
Temperature [K]
real(kind=pr), intent(in) :: a
Molar fraction of the second fluid
real(kind=pr), intent(inout) :: u(:)
Eigen-vector
logical, intent(out) :: found
Found a Critical End Point
type(EquilibriumState), intent(out) :: CEP
Critical End Point
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: Fcep(size(z0)+4)
real(kind=pr), private :: Fcep_new(size(z0)+4)
real(kind=pr), private :: V_cep
real(kind=pr), private :: Xcep(size(z0)+4)
real(kind=pr), private :: alpha
real(kind=pr), private :: dFcep(size(z0)+4,size(z0)+4)
real(kind=pr), private :: dXcep(size(z0)+4)
real(kind=pr), private :: damp
integer, private :: inits
integer, private :: its
integer, private :: nc
real(kind=pr), private :: y_cep(size(z0))
Call graph
look_for_cep calls df_cep, f_cep, get_a, pressure, set_a, solve_system, stability_check
df_cep calls f_cep, get_a
f_cep calls get_a, lambda1, lnfug_vt
pressure calls residual_helmholtz
solve_system calls dgesv
stability_check calls lnfug_vt, volume
lambda1 calls get_a, lnfug_vt, eigen
lnfug_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d
eigen calls dsyev
critical_line calls look_for_cep