min_tpd – yaeos
min_tpd Subroutine
MPL
60 statements
Source File
public subroutine min_tpd(model, z, P, T, mintpd, w, all_minima)
Arguments
Type Intent Optional Attributes Name
class(BaseModel), target :: model
Thermodynamic model
real(kind=pr), intent(in) :: z(:)
Feed composition
real(kind=pr), intent(in) :: P
Pressure [bar]
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(out) :: mintpd
Minimal value of
real(kind=pr), intent(out) :: w(:)
Trial composition
real(kind=pr), intent(out), optional :: all_minima(:,:)
All the found minima
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: V
real(kind=pr), public :: di(size(z))
real(kind=pr), public :: dw(size(w))
real(kind=pr), public :: dx(size(w))
integer, public :: i
integer, public :: iters
integer, public :: j
real(kind=pr), public :: lnphi_w(size(w))
real(kind=pr), public :: lnphi_z(size(z))
integer, public :: max_iters
real(kind=pr), public :: mins(size(w))
integer, public :: nc
integer, public :: stat
real(kind=pr), public :: ws(size(w),size(w))
Call graph
min_tpd calls ln_activity_coefficient, lnphi_pt, tm
tm calls ln_activity_coefficient, lnphi_pt
pt_mp_flash calls min_tpd