newton_1d – yaeos
newton_1d Subroutine
MPL
21 statements
Source File
public subroutine newton_1d(f, x, tol, max_iters, failed)
Arguments
Type Intent Optional Attributes Name
procedure(f_1d) :: f
real(kind=pr), intent(inout) :: x
real(kind=pr), intent(in) :: tol
integer, intent(in) :: max_iters
logical, intent(out) :: failed
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: df
real(kind=pr), public :: fval
integer, public :: i
real(kind=pr), public :: step
Call graph
newton calls newton_1d
volume calls newton
binary_llv_from_cep calls volume
cp_residual_pt calls volume
critical_line calls volume, look_for_cep
critical_point calls volume
cv_residual_pt calls volume
enthalpy_residual_pt calls volume
entropy_residual_pt calls volume
gibbs_residual_pt calls volume
helmholtz_residual_pt calls volume
internal_energy_residual_pt calls volume
lnphi_pt calls volume
psat_pure calls volume
pure_saturation_line calls volume
saturation_pressure calls volume, lnphi_pt, solve_tp
saturation_temperature calls volume, lnphi_pt, solve_tp
stability_check calls volume
find_hpl calls lnphi_pt, pt_envelope_2ph
find_llcl calls lnphi_pt
get_critical_constants calls critical_point, psat_pure
ln_activity_coefficient calls lnphi_pt
look_for_cep calls stability_check
pt_f_np calls lnphi_pt
pt_f_three_phases calls lnphi_pt
px_f_np calls lnphi_pt
px_f_three_phases calls lnphi_pt
refit_rkpr_k calls psat_pure, pure_saturation_line
saturation_tp calls lnphi_pt
tx_f_np calls lnphi_pt
enthalpy_excess calls ln_activity_coefficient
entropy_excess calls ln_activity_coefficient
gibbs_excess calls ln_activity_coefficient
helmholtz_excess calls ln_activity_coefficient
init_pcsaft calls get_critical_constants
internal_energy_excess calls ln_activity_coefficient
px_envelope_2ph calls foo
rkpr calls refit_rkpr_k
solve_generalized_point calls pt_f_np
solve_mp_flash_point calls pt_f_np
solve_point calls pt_f_three_phases, px_f_three_phases, px_f_np, tx_f_np, pt_f_np
tx_envelope_2ph calls foo
volume_excess calls ln_activity_coefficient
create_generalized_isoz_line calls solve_generalized_point
pt_envelope calls solve_point
pt_envelope_3ph calls solve_point
pt_mp_flash calls solve_mp_flash_point
px_envelope calls solve_point
px_envelope_3ph calls solve_point
solve_tp calls wrap
tx_envelope calls solve_point
pt_envelope_2ph calls pt_envelope