nrtl_hv_tdep_linear – yaeos
nrtl_hv_tdep_linear Subroutine
MPL
11 statements
Source File
public elemental subroutine nrtl_hv_tdep_linear(T, A, B, tau, dtaudt, dtaudt2)
nrtl_hv_tdep_linear
Description
Temperature dependent parameters for NRTL model. The temperature dependence is linear:
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(in) :: A
Interaction parameters
real(kind=pr), intent(in) :: B
Interaction parameters
real(kind=pr), intent(out) :: tau
matrix
real(kind=pr), intent(out) :: dtaudt
First derivative of with respect to temperature
real(kind=pr), intent(out) :: dtaudt2
Second derivative of with respect to temperature
Called by
Call graph
excess_gibbs calls nrtl_hv_tdep_linear
dmixhvnrtl calls excess_gibbs