nrtl_hv_ge – yaeos
nrtl_hv_ge Subroutine
MPL
106 statements
Source File
public subroutine nrtl_hv_ge(n, T, b, alpha, tau, dtaudt, dtaudt2, Ge, Gen, GeT, GeT2, GeTn, Gen2)
nrtl_hv_ge
Description
This subroutine calculates the excess Gibbs energy and its derivatives for a mixture using the NRTL model modified by Huron and Vidal. The NRTL model accounts for non-ideal interactions between components in a mixture. The expression for the excess Gibbs energy is:
With:
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: n(:)
Number of moles vector.
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(in) :: b(:)
parameter
real(kind=pr), intent(in) :: alpha(:,:)
matrix
real(kind=pr), intent(in) :: tau(:,:)
matrix
real(kind=pr), intent(in) :: dtaudt(:,:)
First derivative of with respect to temperature
real(kind=pr), intent(in) :: dtaudt2(:,:)
Second derivative of with respect to temperature
real(kind=pr), intent(out), optional :: Ge
Excess Gibbs energy
real(kind=pr), intent(out), optional :: Gen(:)
Excess Gibbs energy derivative with repect to number of moles
real(kind=pr), intent(out), optional :: GeT
Excess Gibbs energy derivative with respect to temperature
real(kind=pr), intent(out), optional :: GeT2
Excess Gibbs energy second derivative with respect to temperature
real(kind=pr), intent(out), optional :: GeTn(:)
Excess Gibbs energy derivative with respect to temperature and number of moles
real(kind=pr), intent(out), optional :: Gen2(:,:)
Excess Gibbs energy second derivative with respect to number of moles
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: D
real(kind=pr), public :: Dn(size(n))
real(kind=pr), public :: E(size(n),size(n))
real(kind=pr), public :: U
real(kind=pr), public :: aux_Ge
real(kind=pr), public :: aux_GeT
real(kind=pr), public :: aux_GeTn(size(n))
real(kind=pr), public :: aux_Gen(size(n))
real(kind=pr), public :: dEdT(size(n),size(n))
real(kind=pr), public :: dEdT2(size(n),size(n))
real(kind=pr), public :: denom
real(kind=pr), public :: eta(size(n),size(n))
real(kind=pr), public :: etaT(size(n),size(n))
integer, public :: i
integer, public :: j
integer, public :: k
integer, public :: l
integer, public :: m
integer, public :: nc
real(kind=pr), public :: omega(size(n),size(n))
real(kind=pr), public :: omegaT(size(n),size(n))
logical, public :: p_ge
logical, public :: p_gen
logical, public :: p_gen2
logical, public :: p_gent
logical, public :: p_get
logical, public :: p_get2
real(kind=pr), public :: theta(size(n),size(n))
real(kind=pr), public :: thetaT(size(n))
real(kind=pr), public :: thetaTT(size(n))
real(kind=pr), public :: xi(size(n),size(n))
real(kind=pr), public :: xiT(size(n))
real(kind=pr), public :: xiTT(size(n))
Call graph
excess_gibbs calls nrtl_hv_ge
dmixhvnrtl calls excess_gibbs