optval_logical – yaeos
optval_logical Function
MPL
9 statements
Source File
public function optval_logical(val, default)
Set a value to a default if it is not defined
Arguments
Type Intent Optional Attributes Name
logical, intent(in), optional :: val
logical, intent(in) :: default
Return Value logical
Called by
Call graph
optval calls optval_logical
pt_envelope calls optval
pt_envelope_2ph calls optval, pt_envelope
px_envelope calls optval
px_envelope_2ph calls optval
saturation_pressure calls optval
saturation_temperature calls optval
tx_envelope calls optval
tx_envelope_2ph calls optval
volume_michelsen calls optval
find_hpl calls pt_envelope_2ph
volume calls volume_michelsen, volume