pressure – yaeos
pressure Subroutine
MPL
22 statements
Source File
private subroutine pressure(eos, n, V, T, P, dPdV, dPdT, dPdn)
Calculate pressure.
Calculate pressure using residual helmholtz models.
Examples
eos = PengRobinson76(Tc, Pc, w)
n = [1.0_pr, 1.0_pr]
T = 300.0_pr
V = 1.0_pr
call eos%pressure(n, V, T, P, dPdV=dPdV, dPdT=dPdT, dPdn=dPdn)
Type Bound
ArModel
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: eos
Model
real(kind=pr), intent(in) :: n(:)
Moles number vector
real(kind=pr), intent(in) :: V
Volume [L]
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(out) :: P
Pressure [bar]
real(kind=pr), intent(out), optional :: dPdV
real(kind=pr), intent(out), optional :: dPdT
real(kind=pr), intent(out), optional :: dPdn(:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: Ar
real(kind=pr), private :: ArTV
real(kind=pr), private :: ArV
real(kind=pr), private :: ArV2
real(kind=pr), private :: ArVn(size(eos))
real(kind=pr), private :: totn
Call graph
pressure calls residual_helmholtz
ar_consistency calls pressure
binary_llv_from_cep calls pressure
critical_point calls pressure
enthalpy_residual_pt calls pressure
entropy_residual_pt calls pressure
gibbs_residual_pt calls pressure
helmholtz_residual_pt calls pressure
internal_energy_residual_pt calls pressure
look_for_cep calls pressure
pressure_equality_v_beta_xy calls pressure
psat_pure calls pressure
critical_line calls look_for_cep
flash calls pressure_equality_v_beta_xy
flash_no_beta_limits calls pressure_equality_v_beta_xy
get_critical_constants calls critical_point, psat_pure
refit_rkpr_k calls psat_pure
init_pcsaft calls get_critical_constants
rkpr calls refit_rkpr_k