Psat_pure – yaeos
Psat_pure Function
MPL
19 statements
Source File
private function Psat_pure(eos, ncomp, T)
Calculation of saturation pressure of a pure component using the secant method.
Type Bound
ArModel
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: eos
Model that will be used
integer, intent(in) :: ncomp
Number of component in the mixture from which the saturation pressure will be calculated
real(kind=pr), intent(in) :: T
Temperature [K]
Return Value real(kind=pr)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: F(3)
real(kind=pr), private :: P
real(kind=pr), private :: Pc
real(kind=pr), private :: S
real(kind=pr), private :: Vl
real(kind=pr), private :: Vv
real(kind=pr), private :: X(3)
real(kind=pr), private :: dF(3,3)
real(kind=pr), private :: dFdS(3)
integer, private :: its
real(kind=pr), private :: n(size(eos))
integer, private, parameter :: ns = 3
Call graph
psat_pure calls pressure, solve_point_psat, volume
pressure calls residual_helmholtz
solve_point_psat calls get_v0, isofugacity, solve_system
volume calls get_v0, newton
newton calls newton_1d
solve_system calls dgesv
lnfug_vt calls residual_helmholtz
get_critical_constants calls psat_pure
refit_rkpr_k calls psat_pure
init_pcsaft calls get_critical_constants
rkpr calls refit_rkpr_k