PSRK – yaeos
PSRK Function
MPL
39 statements
Source File
public function PSRK(tc, pc, w, molecules, c1, c2, c3) result(model)
Uses
yaeos__models_ar_cubic_alphas
yaeos__models_ar_genericcubic
yaeos__models_ge_implementations
yaeos__models_cubic_mixing_rules_huron_vidal
yaeos__models_ge_group_contribution_groups
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: tc(:)
Critical temperature [K]
real(kind=pr), intent(in) :: pc(:)
Critical pressure [bar]
real(kind=pr), intent(in) :: w(:)
Acentric factor
type(Groups), intent(in) :: molecules(:)
real(kind=pr), intent(in), optional :: c1(:)
real(kind=pr), intent(in), optional :: c2(:)
real(kind=pr), intent(in), optional :: c3(:)
Return Value type(CubicEoS)
Calls
Variables
Type Visibility Attributes Name Initial
type(AlphaSoave), private :: alpha
type(AlphaMathiasCopeman), private :: alpha_mc
type(Substances), private :: composition
type(UNIFAC), private :: ge
integer, private :: i
type(MHV), private :: mixrule
integer, private :: nc
Call graph
psrk calls setup_psrk
setup_psrk calls get_subgroups_aij, get_subgroups_bij, get_subgroups_cij, psrkparameters, setup_unifac
get_subgroups_aij calls get_maingroup_index, get_subgroup_maingroup
get_subgroups_bij calls get_maingroup_index, get_subgroup_maingroup
get_subgroups_cij calls get_maingroup_index, get_subgroup_maingroup
setup_unifac calls get_subgroups_aij, check_consistency, get_subgroup_q, get_subgroup_r, thetas_i, unifacparameters
get_subgroup_maingroup calls get_subgroup_index
get_subgroup_q calls get_subgroup_index
get_subgroup_r calls get_subgroup_index
thetas_i calls get_subgroup_q