pt_envelope_2ph – yaeos
pt_envelope_2ph Function
MPL
235 statements
Source File
public function pt_envelope_2ph(model, z, first_point, points, iterations, delta_0, specified_variable_0, solver, stop_conditions, maximum_pressure) result(envelopes)
Uses
yaeos__auxiliar
PT two-phase envelope calculation procedure.
Phase envelope calculation using the continuation method. Defaults to solving the saturation temperature and continues with an increment in it. The variable to specify can be changed by modifying specified_variable_0 with the corresponding variable number.
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Thermodyanmic model
real(kind=pr), intent(in) :: z(:)
Vector of molar fractions
type(EquilibriumState), intent(in) :: first_point
Initial point of the envelope
integer, intent(in), optional :: points
Maxmimum number of points, defaults to 500
integer, intent(in), optional :: iterations
Point solver maximum iterations, defaults to 100
real(kind=pr), intent(in), optional :: delta_0
Initial extrapolation
integer, intent(in), optional :: specified_variable_0
Position of specified variable, since the vector of variables is the values for specification will be for the equilibria constants, for and for .
procedure(continuation_solver), optional :: solver
Specify solver for each point, defaults to a full newton procedure
procedure(continuation_stopper), optional :: stop_conditions
Function that returns true if the continuation method should stop
real(kind=pr), intent(in), optional :: maximum_pressure
Maximum pressure to calculate [bar]
Return Value type(PTEnvel2)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: S0
Initial specification value
real(kind=pr), private :: X(size(z)+2)
Vector of variables used in the continuation method
real(kind=pr), private, allocatable :: XS(:,:)
All the calculated variables that are returned on the continuation method procedure (unused since each point is saved on the fly)
real(kind=pr), private :: dS0
Initial specification step
integer, private :: i
character(len=14), private :: kind
character(len=14), private :: kind_w
character(len=14), private :: kind_x(1)
integer, private :: max_iterations
Maximum number of iterations
integer, private :: max_points
Maximum number of points
type(PTEnvelMP), private :: mp_env
integer, private :: nc
Number of components
integer, private :: ns
Number of specified variable
real(kind=pr), private :: w0(size(z))
real(kind=pr), private :: x_l0(1,size(z))
Subroutines
subroutine detect_critical(X, dXdS, ns, S, dS)
Critical point detection
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(inout) :: X(:)
Vector of variables
real(kind=pr), intent(inout) :: dXdS(:)
Variation of variables wrt S
integer, intent(inout) :: ns
Number of specified variable
real(kind=pr), intent(inout) :: S
Specification value
real(kind=pr), intent(inout) :: dS
Step in specification
subroutine foo(X, ns, S, F, dF, dFdS)
Function that needs to be solved at each envelope point
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: X(:)
integer, intent(in) :: ns
real(kind=pr), intent(in) :: S
real(kind=pr), intent(out) :: F(:)
real(kind=pr), intent(out) :: dF(:,:)
real(kind=pr), intent(out) :: dFdS(:)
subroutine save_point(X, iters)
Save the converged point
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: X(:)
integer, intent(in) :: iters
subroutine update_spec(X, ns, S, dS, dXdS, step_iters)
Update the specification during continuation.
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(inout) :: X(:)
Vector of variables
integer, intent(inout) :: ns
Number of specified variable in the vector
real(kind=pr), intent(inout) :: S
Variable specification value
real(kind=pr), intent(inout) :: dS
Step in specification
real(kind=pr), intent(inout) :: dXdS(:)
Variation of variables with respect to specification
integer, intent(in) :: step_iters
Iterations used in the solver
Call graph
pt_envelope_2ph calls optval, continuation, pt_envelope
optval calls optval_character, optval_integer, optval_real
continuation calls full_newton, solve_system
pt_envelope calls optval, check_critical_jump, detect_critical, get_values_from_x, solve_point, update_specification
check_critical_jump calls interpol
detect_critical calls interpol
full_newton calls solve_system
solve_point calls get_values_from_x, solve_system, pt_f_np
solve_system calls dgesv
update_specification calls solve_system, near_critical
pt_f_np calls dvnvdb, dvnvdlnkl, dvnvdn, dvwdb, dvwdlnkl, lnphi_pt
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d
find_hpl calls pt_envelope_2ph