pt_F_three_phases – yaeos
pt_F_three_phases Subroutine
MPL
78 statements
Source File
private subroutine pt_F_three_phases(model, z, Xvars, ns, S, F, df)
Uses
iso_fortran_env
Function to solve at each point of a three phase envelope.
The vector of variables X corresponds to:
While the equations are:
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
real(kind=pr), intent(in) :: z(:)
real(kind=pr), intent(in) :: Xvars(:)
Vector of variables
integer, intent(in) :: ns
Number of specification
real(kind=pr), intent(in) :: S
Specification value
real(kind=pr), intent(out) :: F(size(Xvars))
Vector of functions valuated
real(kind=pr), intent(out) :: df(size(Xvars),size(Xvars))
Jacobian matrix
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: Kx((Size(Xvars)-3)/2)
real(kind=pr), private :: Ky((Size(Xvars)-3)/2)
real(kind=pr), private :: P
real(kind=pr), private :: T
real(kind=pr), private :: Vw
real(kind=pr), private :: Vx
real(kind=pr), private :: Vy
real(kind=pr), private :: beta
real(kind=pr), private, dimension((Size(Xvars)-3)/2, (Size(Xvars)-3)/2) :: dlnphi_dn_w
real(kind=pr), private, dimension((Size(Xvars)-3)/2, (Size(Xvars)-3)/2) :: dlnphi_dn_x
real(kind=pr), private, dimension((Size(Xvars)-3)/2, (Size(Xvars)-3)/2) :: dlnphi_dn_y
real(kind=pr), private, dimension((Size(Xvars)-3)/2) :: dlnphi_dp_w
real(kind=pr), private, dimension((Size(Xvars)-3)/2) :: dlnphi_dp_x
real(kind=pr), private, dimension((Size(Xvars)-3)/2) :: dlnphi_dp_y
real(kind=pr), private, dimension((Size(Xvars)-3)/2) :: dlnphi_dt_w
real(kind=pr), private, dimension((Size(Xvars)-3)/2) :: dlnphi_dt_x
real(kind=pr), private, dimension((Size(Xvars)-3)/2) :: dlnphi_dt_y
real(kind=pr), private :: dwdKx((Size(Xvars)-3)/2)
real(kind=pr), private :: dwdKy((Size(Xvars)-3)/2)
real(kind=pr), private :: dwdb((Size(Xvars)-3)/2)
real(kind=pr), private :: dxdKx((Size(Xvars)-3)/2)
real(kind=pr), private :: dxdKy((Size(Xvars)-3)/2)
real(kind=pr), private :: dydKx((Size(Xvars)-3)/2)
real(kind=pr), private :: dydKy((Size(Xvars)-3)/2)
integer, private :: i
integer, private :: j
real(kind=pr), private, dimension((Size(Xvars)-3)/2) :: lnphi_w
real(kind=pr), private, dimension((Size(Xvars)-3)/2) :: lnphi_x
real(kind=pr), private, dimension((Size(Xvars)-3)/2) :: lnphi_y
integer, private :: nc
real(kind=pr), private, dimension((Size(Xvars)-3)/2) :: w
real(kind=pr), private, dimension((Size(Xvars)-3)/2) :: x
real(kind=pr), private, dimension((Size(Xvars)-3)/2) :: y
Call graph
pt_f_three_phases calls lnphi_pt
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d
solve_point calls pt_f_three_phases
pt_envelope_3ph calls solve_point