pt_F_NP – yaeos
pt_F_NP Subroutine
MPL
144 statements
Source File
public subroutine pt_F_NP(model, z, np, beta_w, kinds_x, kind_w, X, ns, S, F, df, Vl, Vw)
Uses
iso_fortran_env
Function to solve at each point of a multi-phase envelope.
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Model to use.
real(kind=pr), intent(in) :: z(:)
Mixture global composition.
integer, intent(in) :: np
Number of main phases.
real(kind=pr), intent(in) :: beta_w
Fraction of the reference (incipient) phase.
character(len=14), intent(in) :: kinds_x(np)
Kind of the main phases.
character(len=14), intent(in) :: kind_w
Kind of the reference phase.
real(kind=pr), intent(in) :: X(:)
Vector of variables.
integer, intent(in) :: ns
Number of specification.
real(kind=pr), intent(in) :: S
Specification value.
real(kind=pr), intent(out) :: F(size(X))
Vector of functions valuated.
real(kind=pr), intent(out) :: df(size(X),size(X))
Jacobian matrix.
real(kind=pr), intent(out) :: Vl(np)
real(kind=pr), intent(out) :: Vw
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: K(np,size(z))
real(kind=pr), private :: P
real(kind=pr), private :: T
real(kind=pr), private :: betas(np)
real(kind=pr), private :: dPdN(size(z))
real(kind=pr), private :: dPdT
real(kind=pr), private :: dPdV
real(kind=pr), private :: dVwdP
real(kind=pr), private :: dVwdT
real(kind=pr), private :: dVwdn(size(z))
real(kind=pr), private :: denom(size(z))
real(kind=pr), private :: denomdlnK(np,size(z),size(z))
real(kind=pr), private, dimension(size(z), size(z)) :: dlnphi_dn
real(kind=pr), private, dimension(np, size(z), size(z)) :: dlnphi_dn_l
real(kind=pr), private, dimension(size(z), size(z)) :: dlnphi_dn_w
real(kind=pr), private :: dlnphi_dp(size(z))
real(kind=pr), private, dimension(np, size(z)) :: dlnphi_dp_l
real(kind=pr), private, dimension(size(z)) :: dlnphi_dp_w
real(kind=pr), private :: dlnphi_dt(size(z))
real(kind=pr), private, dimension(np, size(z)) :: dlnphi_dt_l
real(kind=pr), private, dimension(size(z)) :: dlnphi_dt_w
real(kind=pr), private :: dpdT_w
real(kind=pr), private :: dpdn_l(np,size(z))
real(kind=pr), private :: dpdn_w(size(z))
real(kind=pr), private :: dpdt_l(np)
real(kind=pr), private :: dpdv_l(np)
real(kind=pr), private :: dpdv_w
real(kind=pr), private :: dwdb(np,size(z))
real(kind=pr), private :: dwdlnK(np,size(z))
real(kind=pr), private :: dx_l_dlnK(np,np,size(z))
integer, private :: i
integer, private :: idx_1
integer, private :: idx_2
integer, private :: ik
integer, private :: j
integer, private :: l
integer, private :: lb
real(kind=pr), private :: lnphi(size(z))
real(kind=pr), private, dimension(np, size(z)) :: lnphi_l
real(kind=pr), private, dimension(size(z)) :: lnphi_w
real(kind=pr), private :: moles(size(z))
integer, private :: nc
integer, private :: nv
Specified volume for ln(V(nv)/Vw)
integer, private :: phase
integer, private :: ub
real(kind=pr), private, dimension(size(z)) :: w
real(kind=pr), private, dimension(np, size(z)) :: x_l
Call graph
pt_f_np calls lnphi_pt
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d
solve_point calls pt_f_np
pt_envelope calls solve_point
pt_envelope_2ph calls pt_envelope
find_hpl calls pt_envelope_2ph