pt_mp_flash – yaeos
pt_mp_flash Function
MPL
75 statements
Source File
public function pt_mp_flash(model, z, P, T)
Uses
yaeos__equilibria_stability
pt_mp_flash
Perform a multiphase flash calculation at constant zPT.
Description
This method will do stability analysis to detect the possibility of new phases. For each new phase detected it will calculate a multiphase flash and repeat stability analysis until no new phases are detected.
Examples
References
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
real(kind=pr), intent(in) :: z(:)
real(kind=pr), intent(in) :: P
real(kind=pr), intent(in) :: T
Return Value type(MPEquilibriumState)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public, allocatable :: F(:)
real(kind=pr), public :: K(max_phases,size(z))
real(kind=pr), public :: S1
real(kind=pr), public :: S2
real(kind=pr), public, allocatable :: X(:)
real(kind=pr), public :: all_minima(size(z),size(z))
real(kind=pr), public :: beta0
integer, public :: beta_0_index
real(kind=pr), public, allocatable :: betas(:)
integer, public :: iters
character(len=14), public :: kind_w
character(len=14), public :: kinds_x(max_phases)
logical, public :: less_phases
integer, public :: max_iters
integer, public, parameter :: max_phases = 4
real(kind=pr), public :: mintpd
real(kind=pr), public :: mintpd_w
real(kind=pr), public :: mintpd_xl1
integer, public :: nc
integer, public :: np
integer, public :: ns1
integer, public :: ns2
real(kind=pr), public :: w(size(z))
real(kind=pr), public :: w_stab(size(z))
real(kind=pr), public :: x_l(max_phases,size(z))
Call graph
pt_mp_flash calls min_tpd, solve_mp_flash_point
min_tpd calls ln_activity_coefficient, lnphi_pt, tm
solve_mp_flash_point calls pt_f_np, solve_system
pt_f_np calls lnphi_pt
solve_system calls dgesv
tm calls ln_activity_coefficient, lnphi_pt
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d