pure_saturation_line – yaeos
pure_saturation_line Function
MPL
83 statements
Source File
public function pure_saturation_line(model, component, minP, minT) result(pt)
Uses
yaeos__auxiliar
Pure saturation line
Saturation pressures and temperatures for a pure component.
Description
This function calculates the saturation line for a pure component. Starting from the pure component critical point, the function traces the saturation line using the continuation method. The function returns a PurePsat object with the saturation temperatures and pressures. The object also contains interpolators to get the saturation temperature for a given pressure and vice versa.
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Thermodyanmic model
integer, intent(in) :: component
Component index to calculate the line
real(kind=pr), intent(in) :: minP
Minimum pressure [bar]
real(kind=pr), intent(in) :: minT
Minimum temperature [K]
Return Value type(PurePsat)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: F(4)
real(kind=pr), public :: P
real(kind=pr), public :: Pc
real(kind=pr), public :: S
real(kind=pr), public :: T
real(kind=pr), public :: Tc
real(kind=pr), public :: Vc
real(kind=pr), public :: Vx
real(kind=pr), public :: Vy
real(kind=pr), public :: X(4)
Variables [lnVx, lnVy, lnP, lnT]
real(kind=pr), public :: dF(4,4)
real(kind=pr), public :: dFdS(4)
real(kind=pr), public :: dS
real(kind=pr), public :: dX(4)
real(kind=pr), public :: dXdS(4)
integer, public :: i
integer, public :: iP
integer, public :: iT
integer, public :: its
integer, public :: nc
integer, public :: ns
integer, public :: points
real(kind=pr), public :: z(size(model))
Call graph
pure_saturation_line calls initialize, solve_point, solve_system, volume
solve_point calls solve_system, get_v0, isofugacity
solve_system calls dgesv
volume calls get_v0, newton
newton calls newton_1d
lnfug_vt calls residual_helmholtz
refit_rkpr_k calls pure_saturation_line
rkpr calls refit_rkpr_k