px_envelope_3ph – yaeos
px_envelope_3ph Function
MPL
61 statements
Source File
public function px_envelope_3ph(model, z0, zi, T, x0, y0, w0, beta0, P0, a0, ns0, dS0, points) result(envelope)
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
real(kind=pr), intent(in) :: z0(:)
real(kind=pr), intent(in) :: zi(:)
real(kind=pr), intent(in) :: T
real(kind=pr), intent(in) :: x0(:)
real(kind=pr), intent(in) :: y0(:)
real(kind=pr), intent(in) :: w0(:)
real(kind=pr), intent(in) :: beta0
real(kind=pr), intent(in) :: P0
real(kind=pr), intent(in) :: a0
integer, intent(in) :: ns0
real(kind=pr), intent(in) :: dS0
integer, intent(in) :: points
Return Value type(PXEnvel3)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: F(size(z0)*2+3)
real(kind=pr), private :: P(points)
real(kind=pr), private :: S
Specified value
real(kind=pr), private :: Xvars(size(z0)*2+3)
real(kind=pr), private :: a(points)
real(kind=pr), private :: beta(points)
real(kind=pr), private :: dF(size(z0)*2+3,size(z0)*2+3)
real(kind=pr), private :: dS
Specified value step for next point extrapolation
real(kind=pr), private :: dX(size(z0)*2+3)
real(kind=pr), private :: dXdS(size(z0)*2+3)
integer, private :: i
integer, private :: its
real(kind=pr), private :: kx(size(z0))
real(kind=pr), private :: ky(size(z0))
integer, private :: max_its = 500
integer, private :: nc
integer, private :: ns
Specified variable
real(kind=pr), private :: w(points,size(z0))
real(kind=pr), private :: x(points,size(z0))
real(kind=pr), private :: y(points,size(z0))
Call graph
px_envelope_3ph calls detect_critical, get_values_from_x, solve_point, update_specification
detect_critical calls critical_interpol
get_values_from_x calls get_z
solve_point calls px_f_three_phases, solve_system
update_specification calls solve_system
px_f_three_phases calls get_z, lnphi_pt
solve_system calls dgesv
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d