px_envelope – yaeos
px_envelope Function
MPL
117 statements
Source File
public function px_envelope(model, z0, zi, np, T, x_l0, w0, betas0, P0, alpha0, ns0, dS0, beta_w, points, kinds_x, kind_w, max_pressure)
Uses
yaeos__auxiliar
px_envelope
Calculation of a multiphase Px envelope.
Description
Calculates a phase envelope at costant temperature, using a numerical continuation method.
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Model to use.
real(kind=pr), intent(in) :: z0(:)
Original fluid composition.
real(kind=pr), intent(in) :: zi(:)
Other fluid compostion.
integer, intent(in) :: np
Number of phases, without including the reference phaes
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(in) :: x_l0(np,size(z0))
Initial guess for composition of phases.
real(kind=pr), intent(in) :: w0(size(z0))
Initial guess for composition of reference phase.
real(kind=pr), intent(in) :: betas0(np)
Mole fractions of each phase. Excluding the reference phase.
real(kind=pr), intent(in) :: P0
Initial guess for pressure [bar]
real(kind=pr), intent(in) :: alpha0
Initial guess for relation between two fluids
integer, intent(in) :: ns0
First specified variable.
The first nc*np values correspond to the different , which are sorted like .
From nc*np+1 to nc*np + np, the different values.
nc*np+np+1 and cp*np+np+2 are and , respectively.
real(kind=pr), intent(in) :: dS0
First step to extrapolate for next point calculation. After that It will use an adaptive algorithm.
real(kind=pr), intent(in) :: beta_w
Fraction of the reference (incipient) phase.
integer, intent(in), optional :: points
Maximum number of points to calculate.
character(len=14), intent(in), optional :: kinds_x(np)
character(len=14), intent(in), optional :: kind_w
real(kind=pr), intent(in), optional :: max_pressure
Return Value type(PXEnvelMP)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: F(size(z0)*np+np+2)
real(kind=pr), private :: P
real(kind=pr), private :: Pc
real(kind=pr), private :: Pmax
real(kind=pr), private :: S
Specified value
real(kind=pr), private :: X(size(z0)*np+np+2)
real(kind=pr), private :: X0(size(X))
Initial guess for the point
real(kind=pr), private :: X_last_converged(size(X))
Last converged point
real(kind=pr), private :: Xc(size(X))
Critical variables
real(kind=pr), private :: Xold(size(X))
Old vector of variables
real(kind=pr), private :: ac
real(kind=pr), private :: alpha
real(kind=pr), private, allocatable :: alphas(:)
real(kind=pr), private :: betas(np)
real(kind=pr), private :: dF(size(z0)*np+np+2,size(z0)*np+np+2)
real(kind=pr), private :: dS
Step size of the specification for the next point
real(kind=pr), private :: dX(size(z0)*np+np+2)
real(kind=pr), private :: dXdS(size(z0)*np+np+2)
type(MPPoint), private, allocatable :: env_points(:)
logical, private :: found_critical
If true, a critical point was found
integer, private :: i
Point calculation index
integer, private :: iP
integer, private :: ia
integer, private :: inner
Number of times a failed point is retried to converge
integer, private :: its
logical, private :: jumped_critical
If true, a critical point was jumped
integer, private :: lb
Lower bound, index of the first component of a phase
integer, private :: max_iterations = 100
integer, private :: nc
integer, private :: ns
Number of the specified variable
integer, private :: number_of_points
type(MPPoint), private :: point
integer, private :: ub
Upper bound, index of the last component of a phase
real(kind=pr), private :: w(size(z0))
character(len=14), private :: w_kind
character(len=14), private :: x_kinds(np)
real(kind=pr), private :: x_l(np,size(z0))
real(kind=pr), private :: z(size(z0))
Call graph
px_envelope calls optval, check_critical_jump, detect_critical, get_values_from_x, solve_point, update_specification
optval calls optval_character, optval_integer, optval_real
check_critical_jump calls interpol
detect_critical calls interpol
get_values_from_x calls get_z
solve_point calls px_f_np, solve_system
update_specification calls solve_system
px_f_np calls get_z, lnphi_pt
solve_system calls dgesv
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d