px_envelope_2ph – yaeos
px_envelope_2ph Function
MPL
202 statements
Source File
public function px_envelope_2ph(model, z0, alpha0, z_injection, first_point, points, iterations, delta_0, specified_variable_0, solver, stop_conditions) result(envelopes)
Uses
yaeos__auxiliar
PX two-phase envelope calculation procedure.
Phase envelope calculation using the continuation method. Defaults to solving the saturation temperature and continues with an increment in it. The variable to specify can be changed by modifying specified_variable_0 with the corresponding variable number.
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Thermodyanmic model
real(kind=pr), intent(in) :: z0(:)
Vector of molar fractions of the global composition (main phase)
real(kind=pr), intent(in) :: alpha0
First point of
real(kind=pr), intent(in) :: z_injection(:)
Vector of molar fractions of the injection fluid
type(EquilibriumState) :: first_point
integer, intent(in), optional :: points
Maxmimum number of points, defaults to 500
integer, intent(in), optional :: iterations
Point solver maximum iterations, defaults to 100
real(kind=pr), intent(in), optional :: delta_0
Initial extrapolation
integer, intent(in), optional :: specified_variable_0
Position of specified variable, since the vector of variables is the values for specification will be for the equilibria constants, for and for .
procedure(continuation_solver), optional :: solver
Specify solver for each point, defaults to a full newton procedure
procedure(continuation_stopper), optional :: stop_conditions
Function that returns true if the continuation method should stop
Return Value type(PXEnvel2)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: S0
Initial specification value
real(kind=pr), private :: T
real(kind=pr), private :: X(size(z)+2)
real(kind=pr), private, allocatable :: XS(:,:)
real(kind=pr), private :: dS0
Initial specification step
character(len=14), private :: kind
integer, private :: max_iterations
Maximum number of iterations
integer, private :: max_points
Maximum number of points
integer, private :: nc
Number of components
integer, private :: ns
Number of specified variable
real(kind=pr), private :: z(size(z0))
Composition at some point
Subroutines
subroutine detect_critical(X, dXdS, ns, S, dS)
Critical point detection
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(inout) :: X(:)
Vector of variables
real(kind=pr), intent(inout) :: dXdS(:)
Variation of variables wrt S
integer, intent(inout) :: ns
Number of specified variable
real(kind=pr), intent(inout) :: S
Specification value
real(kind=pr), intent(inout) :: dS
Step in specification
recursive subroutine foo(X, ns, S, F, dF, dFdS)
Function that needs to be solved at each envelope point
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: X(:)
integer, intent(in) :: ns
real(kind=pr), intent(in) :: S
real(kind=pr), intent(out) :: F(:)
real(kind=pr), intent(out) :: dF(:,:)
real(kind=pr), intent(out) :: dFdS(:)
subroutine save_point(X, iters)
Save the converged point
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: X(:)
integer, intent(in) :: iters
subroutine update_spec(X, ns, S, dS, dXdS, step_iters)
Update the specification during continuation.
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(inout) :: X(:)
Vector of variables
integer, intent(inout) :: ns
Number of specified variable in the vector
real(kind=pr), intent(inout) :: S
Variable specification value
real(kind=pr), intent(inout) :: dS
Step in specification
real(kind=pr), intent(inout) :: dXdS(:)
Variation of variables with respect to specification
integer, intent(in) :: step_iters
Iterations used in the solver
Call graph
px_envelope_2ph calls df, dfds, dx, f, fdx, fdx2, optval, foo, numdiff, continuation, get_z
optval calls optval_character, optval_integer, optval_logical, optval_real
continuation calls full_newton, solve_system
full_newton calls solve_system
lnphi_pt calls lnphi_vt, volume
solve_system calls dgesv
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d