px_F_three_phases – yaeos
px_F_three_phases Subroutine
MPL
86 statements
Source File
private subroutine px_F_three_phases(model, z0, zi, T, Xvars, ns, S, F, df)
Uses
iso_fortran_env
Function to solve at each point of a three phase envelope.
The vector of variables X corresponds to:
While the equations are:
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
real(kind=pr), intent(in) :: z0(:)
real(kind=pr), intent(in) :: zi(:)
real(kind=pr), intent(in) :: T
real(kind=pr), intent(in) :: Xvars(:)
Vector of variables
integer, intent(in) :: ns
Number of specification
real(kind=pr), intent(in) :: S
Specification value
real(kind=pr), intent(out) :: F(size(Xvars))
Vector of functions valuated
real(kind=pr), intent(out) :: df(size(Xvars),size(Xvars))
Jacobian matrix
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: Kx(size(z0))
real(kind=pr), private :: Ky(size(z0))
real(kind=pr), private :: P
real(kind=pr), private :: Vw
real(kind=pr), private :: Vx
real(kind=pr), private :: Vy
real(kind=pr), private :: alpha
real(kind=pr), private :: beta
real(kind=pr), private, dimension(size(z0), size(z0)) :: dlnphi_dn_w
real(kind=pr), private, dimension(size(z0), size(z0)) :: dlnphi_dn_x
real(kind=pr), private, dimension(size(z0), size(z0)) :: dlnphi_dn_y
real(kind=pr), private, dimension(size(z0)) :: dlnphi_dp_w
real(kind=pr), private, dimension(size(z0)) :: dlnphi_dp_x
real(kind=pr), private, dimension(size(z0)) :: dlnphi_dp_y
real(kind=pr), private, dimension(size(z0)) :: dlnphi_dt_w
real(kind=pr), private, dimension(size(z0)) :: dlnphi_dt_x
real(kind=pr), private, dimension(size(z0)) :: dlnphi_dt_y
real(kind=pr), private :: dwdKx(size(z0))
real(kind=pr), private :: dwdKy(size(z0))
real(kind=pr), private :: dwda(size(z0))
real(kind=pr), private :: dwdb(size(z0))
real(kind=pr), private :: dxdKx(size(z0))
real(kind=pr), private :: dxdKy(size(z0))
real(kind=pr), private :: dydKx(size(z0))
real(kind=pr), private :: dydKy(size(z0))
real(kind=pr), private :: dzda(size(z0))
integer, private :: i
integer, private :: j
real(kind=pr), private, dimension(size(z0)) :: lnphi_w
real(kind=pr), private, dimension(size(z0)) :: lnphi_x
real(kind=pr), private, dimension(size(z0)) :: lnphi_y
integer, private :: nc
real(kind=pr), private, dimension(size(z0)) :: w
real(kind=pr), private, dimension(size(z0)) :: x
real(kind=pr), private, dimension(size(z0)) :: y
real(kind=pr), private :: z(size(z0))
Call graph
px_f_three_phases calls get_z, lnphi_pt
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d
solve_point calls px_f_three_phases
px_envelope_3ph calls solve_point