refit_rkpr_k – yaeos
refit_rkpr_k Subroutine
MPL
33 statements
Source File
public subroutine refit_rkpr_k(model, component)
Uses
yaeos__models_ar_cubic_alphas
yaeos__equilibria_boundaries_pure_saturation
refit_rkpr_k
Refit the parameter of the RKPR EoS to match the acentric factor
Arguments
Type Intent Optional Attributes Name
type(CubicEoS), intent(inout) :: model
The model to be refitted
integer, intent(in) :: component
Component index to refit
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: Pc
type(PurePsat), private :: Psat
real(kind=pr), private :: Psat_i
real(kind=pr), private :: Tc
type(AlphaRKPR), private :: alpha
real(kind=pr), private :: diff
integer, private :: i
real(kind=pr), private :: w
Call graph
refit_rkpr_k calls get_p, psat_pure, pure_saturation_line
get_p calls evaluate
psat_pure calls pressure, solve_point_psat, volume
pure_saturation_line calls initialize, solve_point, solve_system, volume
pressure calls residual_helmholtz
solve_point_psat calls solve_system, get_v0, isofugacity
solve_point calls solve_system, get_v0, isofugacity
solve_system calls dgesv
volume calls get_v0, newton
newton calls newton_1d
lnfug_vt calls residual_helmholtz
rkpr calls refit_rkpr_k