residual_helmholtz – yaeos
residual_helmholtz Subroutine
MPL
95 statements
Source File
private subroutine residual_helmholtz(self, n, v, t, Ar, ArV, ArT, ArTV, ArV2, ArT2, Arn, ArVn, ArTn, Arn2)
Residual Helmholtz model generic interface
Type Bound
ArModelTapenade
Arguments
Type Intent Optional Attributes Name
class(ArModelTapenade), intent(in) :: self
real(kind=pr), intent(in) :: n(:)
real(kind=pr), intent(in) :: v
real(kind=pr), intent(in) :: t
real(kind=pr), intent(out), optional :: Ar
real(kind=pr), intent(out), optional :: ArV
real(kind=pr), intent(out), optional :: ArT
real(kind=pr), intent(out), optional :: ArTV
real(kind=pr), intent(out), optional :: ArV2
real(kind=pr), intent(out), optional :: ArT2
real(kind=pr), intent(out), optional, dimension(size(n)) :: Arn
real(kind=pr), intent(out), optional, dimension(size(n)) :: ArVn
real(kind=pr), intent(out), optional, dimension(size(n)) :: ArTn
real(kind=pr), intent(out), optional :: Arn2(size(n),size(n))
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: arval
real(kind=pr), private :: arvalb
real(kind=pr), private :: arvald
real(kind=pr), private :: arvald0
real(kind=pr), private :: arvaldb
real(kind=pr), private :: arvaldd
real(kind=pr), private :: df(size(n)+2)
real(kind=pr), private :: df2(size(n)+2,size(n)+2)
integer, private :: i
real(kind=pr), private :: nb(size(n))
integer, private :: nc
real(kind=pr), private :: nd(size(n))
real(kind=pr), private :: ndb(size(n))
real(kind=pr), private :: tb
real(kind=pr), private :: td
real(kind=pr), private :: td0
real(kind=pr), private :: tdb
real(kind=pr), private :: vb
real(kind=pr), private :: vd
real(kind=pr), private :: vd0
real(kind=pr), private :: vdb
Functions
function get_ArnX(var)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: var
Return Value real(kind=pr), (size(n))
function get_dArdX2(var)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: var
Return Value real(kind=pr)
Subroutines
subroutine reset_vars()
Arguments
None
Call graph
residual_helmholtz calls ar_b, ar_d_b, get_arnx, get_dardx2, reset_vars