saturation_F – yaeos
saturation_F Subroutine
MPL
61 statements
Source File
public subroutine saturation_F(model, z, X, ns, S, F, dF, dPdVz, dPdVy)
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
real(kind=pr) :: z(size(model))
real(kind=pr), intent(in) :: X(:)
integer, intent(in) :: ns
real(kind=pr), intent(in) :: S
real(kind=pr), intent(out) :: F(:)
real(kind=pr), intent(out), optional :: dF(:,:)
real(kind=pr), intent(out) :: dPdVz
real(kind=pr), intent(out) :: dPdVy
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: Py
real(kind=pr), public :: Pz
real(kind=pr), public :: T
real(kind=pr), public :: Vy
real(kind=pr), public :: Vz
real(kind=pr), public :: dPdTy
real(kind=pr), public :: dPdTz
real(kind=pr), public :: dPdn_y(size(z))
real(kind=pr), public :: dPdn_z(size(z))
real(kind=pr), public :: dlnfug_dP_y(size(model))
real(kind=pr), public :: dlnfug_dP_z(size(model))
real(kind=pr), public :: dlnfug_dT_y(size(model))
real(kind=pr), public :: dlnfug_dT_z(size(model))
real(kind=pr), public :: dlnfug_dV_y(size(model))
real(kind=pr), public :: dlnfug_dV_z(size(model))
real(kind=pr), public :: dlnfug_dn_y(size(model),size(model))
real(kind=pr), public :: dlnfug_dn_z(size(model),size(model))
integer, public :: j
real(kind=pr), public :: lnPspec
real(kind=pr), public :: lnfug_y(size(model))
real(kind=pr), public :: lnfug_z(size(model))
integer, public :: nc
real(kind=pr), public :: y(size(z))
Call graph
saturation_f calls lnfug_vt
lnfug_vt calls residual_helmholtz
solve_vxvyt calls saturation_f