saturation_temperature – yaeos
saturation_temperature Function
MPL
101 statements
Source File
public function saturation_temperature(model, n, p, kind, t0, y0, max_iters)
Uses
yaeos__m_s_sp
yaeos__auxiliar
Saturation temperature calculation function.
Calculates the saturation pressure of a multicomponent mixture with a given molar composition n. It is possible to calculate:
Bubble point: kind="bubble"
Dew point: kind="dew"
Liquid-Liquid point: kind="liquid-liquid" It will first try to converge a solution using a Newton method to solve the equation
updating at each step as the ratio of fugacities of the phases. If the solution does not converge, it will use a full Newton method to solve the system of equations using the variables and .
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in), target :: model
real(kind=pr), intent(in) :: n(:)
Composition vector [moles / molar fraction]
real(kind=pr), intent(in) :: p
Pressure [bar]
character(len=*), intent(in) :: kind
[bubble|dew|liquid-liquid]
real(kind=pr), intent(in), optional :: t0
Initial temperature [K]
real(kind=pr), intent(in), optional :: y0(:)
Initial composition
integer, intent(in), optional :: max_iters
Maximum number of iterations
Return Value type(EquilibriumState)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: S
real(kind=pr), public :: T1
real(kind=pr), public :: T2
real(kind=pr), public :: X(size(n)+2)
real(kind=pr), public :: dlnphi_dt_y(size(n))
real(kind=pr), public :: dlnphi_dt_z(size(n))
real(kind=pr), public :: f
real(kind=pr), public :: f1
real(kind=pr), public :: f2
character(len=50), public :: incipient
logical, public :: is_incipient(size(n))
integer, public :: iterations
integer, public :: its
real(kind=pr), public :: k(size(n))
real(kind=pr), public :: lnfug_y(size(n))
real(kind=pr), public :: lnfug_z(size(n))
real(kind=pr), public :: lnk(size(n))
character(len=50), public :: main
integer, public :: nc
integer, public :: ns
real(kind=pr), public :: step
real(kind=pr), public :: t
real(kind=pr), public :: vy
real(kind=pr), public :: vz
real(kind=pr), public :: y(size(n))
real(kind=pr), public :: z(size(n))
Call graph
saturation_temperature calls optval, k_wilson, lnphi_pt, solve_tp, volume
optval calls optval_character, optval_integer, optval_logical, optval_real
lnphi_pt calls volume, lnphi_vt
solve_tp calls wrap, newton
volume calls get_v0, newton
newton calls newton_1d, solve_system
lnphi_vt calls residual_helmholtz
saturation_tp calls lnphi_pt
solve_system calls dgesv