setup_unifac – yaeos
setup_unifac Function
MPL
67 statements
Source File
public function setup_unifac(molecules, parameters)
Setup UNIFAC
Instantiate a UNIFAC model
Description
Subroutine used to instantiate a UNIFAC model.
Examples
 ! Instantiate an UNIFAC model with ethanol-water mix and calculate gammas
 use yaeos, only: pr, Groups, setup_unifac, UNIFAC
 type(UNIFAC) :: model
 type(Groups) :: molecules(2)
 real(pr) :: ln_gammas(2)
 ! Ethanol definition [CH3, CH2, OH]
 molecules(1)%groups_ids = [1, 2, 14] ! Subgroups ids
 molecules(1)%number_of_groups = [1, 1, 1] ! Subgroups occurrences
 ! Water definition [H2O]
 molecules(2)%groups_ids = [16]
 molecules(2)%number_of_groups = [1]
 ! Model setup
 model = setup_unifac(molecules)
 ! Calculate ln_gammas
 call model%ln_activity_coefficient([0.5_pr, 0.5_pr], 298.0_pr, ln_gammas)
 print *, ln_gammas ! result: 0.18534142000449058    0.40331395945417559
References
Dortmund Data Bank Software & Separation Technology
Arguments
Type Intent Optional Attributes Name
type(Groups), intent(in) :: molecules(:)
Molecules (Group type) objects
type(GeGCModelParameters), intent(in), optional :: parameters
UNIFAC parameters
Return Value type(UNIFAC)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public, allocatable :: Aij(:,:)
integer, public :: gi
integer, public :: i
integer, public :: j
integer, public :: k
type(GeGCModelParameters), public :: params
type(UNIFACPsi), public :: psi_function
real(kind=pr), public, allocatable :: qks(:)
type(Groups), public :: soup
integer, public, allocatable :: vij(:,:)
Call graph
setup_unifac calls check_consistency, get_subgroup_q, get_subgroup_r, get_subgroups_aij, thetas_i, unifacparameters
get_subgroup_q calls get_subgroup_index
get_subgroup_r calls get_subgroup_index
get_subgroups_aij calls get_maingroup_index, get_subgroup_maingroup
thetas_i calls get_subgroup_q
get_subgroup_maingroup calls get_subgroup_index
setup_dortmund calls setup_unifac
setup_psrk calls setup_unifac
psrk calls setup_psrk