setup_psrk – yaeos
setup_psrk Function
MPL
34 statements
Source File
public function setup_psrk(molecules, parameters)
Uses
yaeos__models_ge_group_contribution_unifac_parameters
Arguments
Type Intent Optional Attributes Name
type(Groups), intent(in) :: molecules(:)
type(GeGCModelParameters), intent(in), optional :: parameters
Return Value type(UNIFAC)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public, allocatable :: Aij(:,:)
real(kind=pr), public, allocatable :: Bij(:,:)
real(kind=pr), public, allocatable :: Cij(:,:)
integer, public :: i
integer, public :: j
integer, public :: ng
type(GeGCModelParameters), public :: params
type(QuadraticPsi), public :: psi_function
type(Groups), public :: soup
Call graph
setup_psrk calls get_subgroups_aij, get_subgroups_bij, get_subgroups_cij, psrkparameters, setup_unifac
get_subgroups_aij calls get_maingroup_index, get_subgroup_maingroup
get_subgroups_bij calls get_maingroup_index, get_subgroup_maingroup
get_subgroups_cij calls get_maingroup_index, get_subgroup_maingroup
setup_unifac calls get_subgroups_aij, check_consistency, get_subgroup_q, get_subgroup_r, thetas_i, unifacparameters
get_subgroup_maingroup calls get_subgroup_index
get_subgroup_q calls get_subgroup_index
get_subgroup_r calls get_subgroup_index
thetas_i calls get_subgroup_q
psrk calls setup_psrk