setup_pr76 – Yaeos
setup_pr76 Subroutine
MIT
22 statements
Source File
public subroutine setup_pr76(n, tc_in, pc_in, w_in, kij_in, lij_in)
Setup the enviroment to use the PengRobinson 76 Equation of State It uses the Cubic Van der Waals mixing rules
Arguments
Type Intent Optional Attributes Name
integer :: n
real(kind=pr) :: tc_in(n)
real(kind=pr) :: pc_in(n)
real(kind=pr) :: w_in(n)
real(kind=pr) :: kij_in(n,n)
real(kind=pr) :: lij_in(n,n)
Calls
Contents
Variables
ac b c del1 del2 k pc tc w
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: ac(n)
real(kind=pr), private :: b(n)
real(kind=pr), private :: c(n)
real(kind=pr), private :: del1(n)
real(kind=pr), private :: del2(n)
real(kind=pr), private :: k(n)
real(kind=pr), private :: pc(n)
real(kind=pr), private :: tc(n)
real(kind=pr), private :: w(n)
Call graph
setup_pr76 calls set_parameters, setup_classicvdw, set_functions, set_ar_function