solve_rr – yaeos
solve_rr Subroutine
MPL
21 statements
Source File
public subroutine solve_rr(z, K, beta, beta_min, beta_max)
solve_rr
Description
Solve the Rachford-Rice Equation using the Newton method.
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: z(:)
Mole fractions vector
real(kind=pr), intent(in) :: K(:)
K-factors
real(kind=pr), intent(out) :: beta
value
real(kind=pr), intent(out) :: beta_min
Lower limit for
real(kind=pr), intent(out) :: beta_max
Upper limit for
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: dgdb
real(kind=pr), public :: g
real(kind=pr), public :: step
Call graph
solve_rr calls betalimits, rachford_rice
flash calls solve_rr
flash_no_beta_limits calls solve_rr