solve_system – yaeos
solve_system Function
MPL
30 statements
Source File
public function solve_system(a, b) result(x)
Uses
iso_fortran_env
Solve a linear sytem AX = b
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: a(size(b),size(b))
real(kind=pr), intent(in) :: b(:)
Return Value real(kind=pr), (size(b))
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: a_lapack(size(b),size(b))
real(kind=dp), public :: b_lapack(size(b))
integer, public, parameter :: dp = selected_real_kind(15)
integer, public :: info
integer, public :: ipiv(size(b))
integer, public :: lda
integer, public :: ldb
integer, public :: n
integer, public :: nrhs
Interfaces
interface
subroutine dgesv(n, nrhs, a, lda, ipiv, b, ldb, info)
Arguments
Type Intent Optional Attributes Name
integer :: n
integer :: nrhs
real(kind=dp) :: a(n,n)
integer :: lda
integer :: ipiv(n)
real(kind=dp) :: b(n)
integer :: ldb
integer :: info
Call graph
solve_system calls dgesv
binary_llv_from_cep calls solve_system, three_phase_line_f_solve
continuation calls solve_system, full_newton
create_generalized_isoz_line calls solve_system, solve_generalized_point
critical_line calls solve_system, look_for_cep
critical_point calls solve_system
full_newton calls solve_system
intersects calls solve_system
look_for_cep calls solve_system
newton calls solve_system
newton_solve calls solve_system
pure_saturation_line calls solve_system, solve_point
solve_generalized_point calls solve_system
solve_mp_flash_point calls solve_system
solve_point calls solve_system
solve_point_psat calls solve_system
solve_vxvyt calls solve_system
three_phase_line_f_solve calls solve_system
update_specification calls solve_system
get_critical_constants calls critical_point, psat_pure
homotopy calls newton
intersect_one_line calls intersects
psat_pure calls solve_point_psat
pt_envelope calls solve_point, update_specification
pt_envelope_3ph calls solve_point, update_specification
pt_mp_flash calls solve_mp_flash_point
px_envelope calls solve_point, update_specification
px_envelope_2ph calls continuation
px_envelope_3ph calls solve_point, update_specification
refit_rkpr_k calls pure_saturation_line, psat_pure
solve_tp calls newton
tx_envelope calls solve_point, update_specification
tx_envelope_2ph calls continuation
init_pcsaft calls get_critical_constants
pt_envelope_2ph calls pt_envelope
rkpr calls refit_rkpr_k
saturation_pressure calls solve_tp
saturation_temperature calls solve_tp
find_hpl calls pt_envelope_2ph