solve_TP – yaeos
solve_TP Subroutine
MPL
38 statements
Source File
public subroutine solve_TP(model, kind, z, X, ns, S, tol, max_iterations, its)
Uses
nonlinear_solvers
yaeos__math
yaeos__math_nonlinearsolvers
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
character(len=*), intent(in) :: kind
real(kind=pr), intent(in) :: z(:)
real(kind=pr), intent(inout) :: X(:)
integer, intent(in) :: ns
real(kind=pr), intent(in) :: S
real(kind=pr), intent(in) :: tol
integer, intent(in) :: max_iterations
integer, intent(out) :: its
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: F(size(X))
real(kind=pr), public :: G(size(X))
real(kind=pr), public :: H(size(X))
real(kind=pr), public :: Jp(size(X))
real(kind=pr), public :: X0(size(X))
real(kind=pr), public :: Xnew(size(X))
real(kind=pr), public :: alpha
real(kind=pr), public :: dF(size(X),size(X))
real(kind=pr), public :: dFdS(size(X))
real(kind=pr), public :: dG(size(X),size(X))
real(kind=pr), public :: dH(size(X),size(X))
real(kind=pr), public :: dx(size(X))
real(kind=pr), public :: grad_phi_p
integer, public :: info
integer, public :: nc
real(kind=pr), public :: phi_ax
real(kind=pr), public :: phi_x
real(kind=pr), public :: t
Subroutines
subroutine wrap(X, F, J)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: X(:)
real(kind=pr), intent(out) :: F(:)
real(kind=pr), intent(out) :: J(:,:)
Call graph
solve_tp calls wrap, newton
newton calls solve_system, newton_1d
saturation_tp calls lnphi_pt
solve_system calls dgesv
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
saturation_pressure calls solve_tp
saturation_temperature calls solve_tp