solve_point – yaeos
solve_point Subroutine
MPL
44 statements
Source File
private subroutine solve_point(model, z0, zi, np, T, beta_w, x_kinds, w_kind, X, ns, S, dXdS, F, df, iters, max_iterations)
Uses
yaeos__math
iso_fortran_env
solve_point
Solve the system of equations for a multiphase point.
Description
Solves the point of a multiphase system using the Newton-Raphson method. The system of equations is defined in px_F_NP
Type Bound
PXEnvelMP
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Model to use.
real(kind=pr), intent(in) :: z0(:)
First mixture composition.
real(kind=pr), intent(in) :: zi(:)
Second mixture composition.
integer, intent(in) :: np
Number of main phases
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(in) :: beta_w
Fraction of the reference (incipient) phase
character(len=14), intent(in) :: x_kinds(np)
character(len=14), intent(in) :: w_kind
real(kind=pr), intent(inout) :: X(:)
Vector of variables
integer, intent(in) :: ns
Number of specification
real(kind=pr), intent(in) :: S
Specification value
real(kind=pr), intent(in) :: dXdS(size(X))
Sensitivity of the variables wrt the specification
real(kind=pr), intent(out) :: F(size(X))
Vector of functions valuated
real(kind=pr), intent(out) :: df(size(X),size(X))
Jacobian matrix
integer, intent(out) :: iters
Number of iterations needed to converge the point
integer, intent(in) :: max_iterations
Maximum number of iterations to solve the point
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: X0(size(X))
real(kind=pr), private :: dX(size(X))
integer, private :: iP
integer, private :: ia
integer, private :: nc
Call graph
solve_point calls px_f_np, solve_system
px_f_np calls get_z, lnphi_pt
solve_system calls dgesv
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d
px_envelope calls solve_point