solve_point – yaeos
solve_point Subroutine
MPL
34 statements
Source File
public subroutine solve_point(model, z0, zi, T, ns, S, X, F, dF, its, maxits)
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
real(kind=pr), intent(in) :: z0(:)
real(kind=pr), intent(in) :: zi(:)
real(kind=pr), intent(in) :: T
integer, intent(in) :: ns
real(kind=pr), intent(in) :: S
real(kind=pr), intent(inout) :: X(:)
real(kind=pr), intent(out) :: F(:)
real(kind=pr), intent(out) :: dF(:,:)
integer, intent(inout) :: its
integer, intent(in) :: maxits
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: dX(size(X))
integer, private :: nc
Call graph
solve_point calls px_f_three_phases, solve_system
px_f_three_phases calls get_z, lnphi_pt
solve_system calls dgesv
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d
px_envelope_3ph calls solve_point