solve_point_psat – yaeos
solve_point_psat Subroutine
MPL
66 statements
Source File
private subroutine solve_point_psat(model, ncomp, nc, X, ns, S, F, dF, dFdS, its)
Uses
yaeos__math
Solve point
Solve a saturation point for a pure component.
Description
The set of equations to solve is:
Where is an specification function defined as:
The vector of variables is equal to .
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Thermodynamic model
integer, intent(in) :: ncomp
Component index
integer, intent(in) :: nc
Total number of components
real(kind=pr), intent(inout) :: X(3)
Variables
integer, intent(in) :: ns
Variable index to solve. If the
real(kind=pr), intent(in) :: S
Variable value specified to solve
real(kind=pr), intent(out) :: F(3)
Function
real(kind=pr), intent(out) :: dF(3,3)
Jacobian
real(kind=pr), intent(out) :: dFdS(3)
Derivative of the function with respect to S
integer, intent(out) :: its
Number of iterations
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: B
real(kind=pr), private :: Py
real(kind=pr), private :: Pz
real(kind=pr), private :: T
real(kind=pr), private :: Vy
real(kind=pr), private :: Vz
real(kind=pr), private :: Xnew(3)
real(kind=pr), private :: dPdTy
real(kind=pr), private :: dPdTz
real(kind=pr), private :: dPdVy
real(kind=pr), private :: dPdVz
real(kind=pr), private :: dX(3)
real(kind=pr), private :: dlnfdt_y(nc)
real(kind=pr), private :: dlnfdt_z(nc)
real(kind=pr), private :: dlnfdv_y(nc)
real(kind=pr), private :: dlnfdv_z(nc)
integer, private :: i
real(kind=pr), private :: lnfug_y(nc)
real(kind=pr), private :: lnfug_z(nc)
real(kind=pr), private :: z(nc)
Subroutines
subroutine isofugacity(X, F, dF, dFdS)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(inout) :: X(3)
real(kind=pr), intent(out) :: F(3)
real(kind=pr), intent(out) :: dF(3,3)
real(kind=pr), intent(out) :: dFdS(3)
Call graph
solve_point_psat calls get_v0, isofugacity, solve_system
solve_system calls dgesv
lnfug_vt calls residual_helmholtz
psat_pure calls solve_point_psat
get_critical_constants calls psat_pure
refit_rkpr_k calls psat_pure
init_pcsaft calls get_critical_constants
rkpr calls refit_rkpr_k