solve_point – yaeos
solve_point Subroutine
MPL
66 statements
Source File
private subroutine solve_point(model, z, np, beta_w, kinds_x, kind_w, X, ns, S, dXdS, F, df, Vl, Vw, iters, max_iterations)
Uses
stdlib_linalg
iso_fortran_env
yaeos__math
Type Bound
PTEnvelMP
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Model to use.
real(kind=pr), intent(in) :: z(:)
Mixture global composition.
integer, intent(in) :: np
Number of main phases
real(kind=pr), intent(in) :: beta_w
Fraction of the reference (incipient) phase
character(len=14), intent(in) :: kinds_x(np)
Kind of the main phases
character(len=14), intent(in) :: kind_w
Kind of the reference phase
real(kind=pr), intent(inout) :: X(:)
Vector of variables
integer, intent(in) :: ns
Number of specification
real(kind=pr), intent(in) :: S
Specification value
real(kind=pr), intent(in) :: dXdS(size(X))
real(kind=pr), intent(out) :: F(size(X))
Vector of functions valuated
real(kind=pr), intent(out) :: df(size(X),size(X))
Jacobian matrix
real(kind=pr), intent(out) :: Vl(np)
Main phases volumes
real(kind=pr), intent(out) :: Vw
Reference phase volume
integer, intent(out) :: iters
Number of iterations to solve the current point
integer, intent(in) :: max_iterations
Maximum number of iterations to solve the point
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: G(size(X))
real(kind=pr), private :: H(size(X))
real(kind=pr), private :: X0(size(X))
logical, private :: can_solve
real(kind=pr), private :: dG(size(X),size(X))
real(kind=pr), private :: dH(size(X),size(X))
real(kind=pr), private :: dX(size(X))
integer, private :: i
integer, private :: iBetas(np)
Indices of the betas in X
integer, private :: iP
Pressure index
integer, private :: iT
Temperature index
integer, private :: l
Phase index
integer, private :: nc
Number of components
real(kind=pr), private :: t
Call graph
solve_point calls eye, pt_f_np, solve_system
pt_f_np calls dvnvdb, dvnvdlnkl, dvnvdn, dvwdb, dvwdlnkl, lnphi_pt
solve_system calls dgesv
lnphi_pt calls lnphi_vt, volume
lnphi_vt calls residual_helmholtz
volume calls get_v0, newton
newton calls newton_1d
pt_envelope calls solve_point