TERMO – yaeos
TERMO Subroutine
MPL
52 statements
Source File
public subroutine TERMO(nc, mtyp, indic, t, p, rn, v, PHILOG, DLPHIP, DLPHIT, FUGN)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nc
Number of components
integer, intent(in) :: mtyp
Type of root desired (-1 vapor, 1 liquid, 0 lower Gr)
integer, intent(in) :: indic
Desired element, this should be setted with optionals
real(kind=pr), intent(in) :: t
Temperature [K]
real(kind=pr), intent(in) :: p
Pressure [bar]
real(kind=pr), intent(in) :: rn(nc)
Mixture mole numbers
real(kind=pr), intent(out) :: v
Volume [L]
real(kind=pr), intent(out) :: PHILOG(nc)
ln(phi*p) vector
real(kind=pr), intent(out), optional :: DLPHIP(nc)
ln(phi) Presssure derivative
real(kind=pr), intent(out), optional :: DLPHIT(nc)
ln(phi) Temp derivative
real(kind=pr), intent(out), optional :: FUGN(nc,nc)
ln(phi) compositional derivative
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: ArTn(nc)
real(kind=pr), public :: ArVn(nc)
real(kind=pr), public :: Arn(nc)
real(kind=pr), public :: Arn2(nc,nc)
real(kind=pr), public :: DPDN(nc)
real(kind=pr), public :: RT
real(kind=pr), public :: Z
real(kind=pr), public :: ar
real(kind=pr), public :: artv
real(kind=pr), public :: arv
real(kind=pr), public :: arv2
real(kind=pr), public :: dpdt
real(kind=pr), public :: dpv
integer, public :: i
integer, public :: igz
integer, public :: k
integer, public :: nder
integer, public :: ntemp
real(kind=pr), public :: totn
Call graph
termo calls arvnder, vcalc
vcalc calls arvnder