thetas_i – yaeos
thetas_i Function
MPL
29 statements
Source File
public function thetas_i(nm, ng, parameters, stew, molecules) result(thetas_ij)
calculation
Calculate the area fraciton of each froup on each molecule.
Description
Calculate the area fraciton of each froup on each molecule. The values are obtained on the setup_unifac function and stored on the UNIFAC type, since the values can be reused (no compositional or temperature dependence)
References
SINTEF - Thermopack
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nm
Number of molecules
integer, intent(in) :: ng
Number of groups
type(GeGCModelParameters), intent(in) :: parameters
UNIFAC parameters
type(Groups), intent(in) :: stew
All the groups present in the system
type(Groups), intent(in) :: molecules(:)
Molecules
Return Value real(kind=pr), (nm,ng)
Group j area fraction on molecule i
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: gi
integer, public :: i
integer, public :: j
integer, public :: k
real(kind=pr), public :: qki_contribution
real(kind=pr), public :: total_area_i(nm)
Call graph
thetas_i calls get_subgroup_q
get_subgroup_q calls get_subgroup_index
setup_unifac calls thetas_i
setup_dortmund calls setup_unifac
setup_psrk calls setup_unifac
psrk calls setup_psrk