three_phase_line_F – yaeos
three_phase_line_F Subroutine
MPL
132 statements
Source File
public subroutine three_phase_line_F(model, Xvars, ns, S, F, dF)
Uses
yaeos__math
three_phase_line_F
Description
Calculate the function vector and Jacobian for the three-phase line (LLV) of a binary mixture. Phases are defined as x, y and w. Which are two liquid phases and one vapor phase respectively.
The system of equations is defined as:
References
[1] M. Cismondi, M.L. Michelsen, Global phase equilibrium calculations: Critical lines, critical end points and liquid–liquid–vapour equilibrium in binary mixtures, The Journal of Supercritical Fluids 39 (2007) 287–295. https://doi.org/10.1016/j.supflu.2006.03.011.
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: model
Thermodynamic model to use
real(kind=pr), intent(in) :: Xvars(:)
Input vector
integer, intent(in) :: ns
Specified variable index
real(kind=pr), intent(in) :: S
Specified variable value
real(kind=pr), intent(out) :: F(:)
Function vector
real(kind=pr), intent(out) :: dF(:,:)
Jacobian
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: Peq_1
real(kind=pr), private :: Peq_2
real(kind=pr), private :: Pw
real(kind=pr), private :: Px
real(kind=pr), private :: Py
real(kind=pr), private :: T
real(kind=pr), private :: dPwdN(2)
real(kind=pr), private :: dPwdT
real(kind=pr), private :: dPwdV
real(kind=pr), private :: dPxdN(2)
real(kind=pr), private :: dPxdT
real(kind=pr), private :: dPxdV
real(kind=pr), private :: dPydN(2)
real(kind=pr), private :: dPydT
real(kind=pr), private :: dPydV
real(kind=pr), private :: dlnfwdP(2)
real(kind=pr), private :: dlnfwdT(2)
real(kind=pr), private :: dlnfwdn(2,2)
real(kind=pr), private :: dlnfwdv(2)
real(kind=pr), private :: dlnfxdP(2)
real(kind=pr), private :: dlnfxdT(2)
real(kind=pr), private :: dlnfxdn(2,2)
real(kind=pr), private :: dlnfxdv(2)
real(kind=pr), private :: dlnfydP(2)
real(kind=pr), private :: dlnfydT(2)
real(kind=pr), private :: dlnfydn(2,2)
real(kind=pr), private :: dlnfydv(2)
real(kind=pr), private :: dxdn(2,2)
real(kind=pr), private :: isofug_1(2)
real(kind=pr), private :: isofug_2(2)
real(kind=pr), private :: lnf_w(2)
real(kind=pr), private :: lnf_x(2)
real(kind=pr), private :: lnf_y(2)
real(kind=pr), private :: vw
real(kind=pr), private :: vx
real(kind=pr), private :: vy
real(kind=pr), private :: w(2)
real(kind=pr), private :: w1
real(kind=pr), private :: x(2)
real(kind=pr), private :: x1
real(kind=pr), private :: y(2)
real(kind=pr), private :: y1
Call graph
three_phase_line_f calls lnfug_vt
lnfug_vt calls residual_helmholtz
three_phase_line_f_solve calls three_phase_line_f
binary_llv_from_cep calls three_phase_line_f_solve