VCALC – Yaeos
VCALC Subroutine
MPL
65 statements
Source File
public recursive subroutine VCALC(self, ITYP, nc, rn, T, P, V, max_iters)
Uses
stdlib_optval
iso_fortran_env
ROUTINE FOR CALCULATION OF VOLUME, GIVEN PRESSURE
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: self
integer, intent(in) :: ITYP
Type of root [-1: vapor, 1:liquid, 0:lower Gibbs energy phase]
integer, intent(in) :: nc
Number of components
real(kind=pr), intent(in) :: rn(nc)
Mixture moles
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(in) :: P
Pressure [bar]
real(kind=pr), intent(out) :: V
Volume [L]
integer, intent(in), optional :: max_iters
Maxiumum number of iterations, defaults to 100
Calls
Called by
Contents
Variables
AT AVAP Ar ArV ArV2 B CPV FIRST_RUN S3R VVAP ZETA ZETMAX ZETMIN del der iter maximum_iterations pcalc totn
Variables
Type Visibility Attributes Name Initial
real(kind=pr), public :: AT
real(kind=pr), public :: AVAP
real(kind=pr), public :: Ar
real(kind=pr), public :: ArV
real(kind=pr), public :: ArV2
real(kind=pr), public :: B
real(kind=pr), public :: CPV
logical, public :: FIRST_RUN
real(kind=pr), public :: S3R
real(kind=pr), public :: VVAP
real(kind=pr), public :: ZETA
real(kind=pr), public :: ZETMAX
real(kind=pr), public :: ZETMIN
real(kind=pr), public :: del
real(kind=pr), public :: der
integer, public :: iter
integer, public :: maximum_iterations
real(kind=pr), public :: pcalc
real(kind=pr), public :: totn
Call graph
vcalc calls optval
fugacity_tp calls vcalc
flash calls fugacity_tp