volume – yaeos
volume Subroutine
MPL
53 statements
Source File
public subroutine volume(eos, n, P, T, V, root_type)
Uses
yaeos__math
Volume solver routine for residual Helmholtz models.
Solves volume roots using newton method. Given pressure and temperature.
Description
This subroutine solves the volume using a newton method. The variable root_type is used to specify the desired root to solve. The options are: ["liquid", "vapor", "stable"]
Examples
eos = PengRobinson76(Tc, Pc, w)
n = [1.0_pr, 1.0_pr]
T = 300.0_pr
P = 1.0_pr
call eos%volume(n, P, T, V, root_type="liquid")
call eos%volume(n, P, T, V, root_type="vapor")
call eos%volume(n, P, T, V, root_type="stable")
Type Bound
ArModel
Arguments
Type Intent Optional Attributes Name
class(ArModel), intent(in) :: eos
Model
real(kind=pr), intent(in) :: n(:)
Moles number vector
real(kind=pr), intent(in) :: P
Pressure [bar]
real(kind=pr), intent(in) :: T
Temperature [K]
real(kind=pr), intent(out) :: V
Volume [L]
character(len=*), intent(in) :: root_type
Desired root-type to solve. Options are: ["liquid", "vapor", "stable"]
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=pr), private :: Gr
real(kind=pr), private :: GrL
real(kind=pr), private :: GrV
real(kind=pr), private :: Vliq
real(kind=pr), private :: Vvap
logical, private :: failed
integer, private :: max_iters = 30
real(kind=pr), private :: tol = 1e-8
real(kind=pr), private :: totnRT
Subroutines
subroutine foo(x, f, df)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: x
real(kind=pr), intent(out) :: f
real(kind=pr), intent(out) :: df
Call graph
volume calls get_v0, newton
newton calls newton_1d
binary_llv_from_cep calls volume
cp_residual_pt calls volume
critical_line calls volume, look_for_cep
critical_point calls volume
cv_residual_pt calls volume
enthalpy_residual_pt calls volume
entropy_residual_pt calls volume
gibbs_residual_pt calls volume
helmholtz_residual_pt calls volume
internal_energy_residual_pt calls volume
lnphi_pt calls volume
psat_pure calls volume
pure_saturation_line calls volume
saturation_pressure calls volume, lnphi_pt, solve_tp
saturation_temperature calls volume, lnphi_pt, solve_tp
stability_check calls volume
find_hpl calls lnphi_pt, pt_envelope_2ph
find_llcl calls lnphi_pt
get_critical_constants calls critical_point, psat_pure
ln_activity_coefficient calls lnphi_pt
look_for_cep calls stability_check
pt_f_np calls lnphi_pt
pt_f_three_phases calls lnphi_pt
px_f_np calls lnphi_pt
px_f_three_phases calls lnphi_pt
refit_rkpr_k calls psat_pure, pure_saturation_line
saturation_tp calls lnphi_pt
tx_f_np calls lnphi_pt
enthalpy_excess calls ln_activity_coefficient
entropy_excess calls ln_activity_coefficient
gibbs_excess calls ln_activity_coefficient
helmholtz_excess calls ln_activity_coefficient
init_pcsaft calls get_critical_constants
internal_energy_excess calls ln_activity_coefficient
px_envelope_2ph calls foo
rkpr calls refit_rkpr_k
solve_generalized_point calls pt_f_np
solve_mp_flash_point calls pt_f_np
solve_point calls tx_f_np, pt_f_three_phases, pt_f_np, px_f_np, px_f_three_phases
tx_envelope_2ph calls foo
volume_excess calls ln_activity_coefficient
create_generalized_isoz_line calls solve_generalized_point
pt_envelope calls solve_point
pt_envelope_3ph calls solve_point
pt_mp_flash calls solve_mp_flash_point
px_envelope calls solve_point
px_envelope_3ph calls solve_point
solve_tp calls wrap
tx_envelope calls solve_point
pt_envelope_2ph calls pt_envelope