! ------------------------------------------------------------------------------
! Declarations
! ------------------------------------------------------------------------------
#:def ar_chain_declaration(AR_CHAIN)
   #:if AR_CHAIN == "Chapman-PCSAFT"
      real(8) :: g_ii
      real(8) :: di_2
      real(8) :: ar_chain
   #:endif
#:enddef ar_chain_declaration

! ------------------------------------------------------------------------------
! Code
! ------------------------------------------------------------------------------
#:def ar_chain(AR_CHAIN)
   #:if AR_CHAIN == "Chapman-PCSAFT"
      ar_chain = 0.0_8

      do i = 1, size(x)
         di_2 = d(i) / 2.0_8

         g_ii = (1.0_8 / eta) + &
            (3.0_8 * di_2 * zetas(2)) / (eta**2) + &
            (2.0_8 * (di_2**2) * (zetas(2)**2)) / (eta**3)

         ! Summation
         ar_chain = ar_chain - x(i) * (m(i) - 1.0_8) * log(g_ii)
      end do
   #:endif
#:enddef ar_chain
