! ------------------------------------------------------------------------------
! Declarations
! ------------------------------------------------------------------------------
#:def ar_hard_sphere_declaration(AR_HARD_SPHERE)
   #:if AR_HARD_SPHERE == "Boublik-Mansoori-Carnahan-Starling"
      real(8) :: term1_hs, term2_hs, term3_hs, one_m_z3_hs
      real(8) :: ar_hs
   #:endif
#:enddef ar_hard_sphere_declaration

! ------------------------------------------------------------------------------
! Code
! ------------------------------------------------------------------------------
#:def ar_hard_sphere(AR_HARD_SPHERE)
   #:if AR_HARD_SPHERE == "Boublik-Mansoori-Carnahan-Starling"
      one_m_z3_hs = 1.0_8 - zeta(3)

      term1_hs = (3.0_8 * zeta(1) * zeta(2)) / one_m_z3_hs
      term2_hs = (zeta(2)**3) / (zeta(3) * (one_m_z3_hs**2))
      term3_hs = ((zeta(2)**3)/(zeta(3)**2) - zeta(0)) * log(one_m_z3_hs)

      ar_hs = (1.0_8 / zeta(0)) * (term1_hs + term2_hs + term3_hs) ! A_hs/RT
   #:endif
#:enddef ar_hard_sphere
