! ------------------------------------------------------------------------------
! Declarations
!
! Please, as you may notice, always use the SAFTs diameter as the variable "d"
! do not redeclare it or recalculate it in the other terms. In the template this
! is the first thing that is evaluated.
! ------------------------------------------------------------------------------
#:def diameter_declaration(DIAMETER)
      real(8) :: d(size(n))
#:enddef diameter_declaration


! ------------------------------------------------------------------------------
! Code
!
! SAFT's diameter implementations, add new ones here in the if structure.
! ------------------------------------------------------------------------------
#:def diameter(DIAMETER)
   #:if DIAMETER == "PCSAFT-DIAMETER"
      do i = 1, size(n)
         d(i) = sigma(i) * (1.0_8 - 0.12_8 * exp(-3.0_8 * epsilon_k(i) / t))
      end do
   #:endif
#:enddef diameter
