! ------------------------------------------------------------------------------
! Declarations
! ------------------------------------------------------------------------------
#:def diameter_declaration(DIAMETER)
      real(8) :: d(size(n))
#:enddef diameter_declaration


! ------------------------------------------------------------------------------
! Code
! ------------------------------------------------------------------------------
#:def diameter(DIAMETER)
   #:if DIAMETER == "PCSAFT-DIAMETER"
      do i = 1, size(n)
         d(i) = sigma(i) * (1.0_8 - 0.12_8 * exp(-3.0_8 * epsilon_k(i) / t))
      end do
   #:endif
#:enddef diameter
