! ------------------------------------------------------------------------------
! Declarations
!
! Please, as you may notice, always use the SAFTs zetas as the variable "zetas"
! do not redeclare it or recalculate it in the other terms. In the template
! this is the second thing that is evaluated (first comes diameter "d"). The
! other variables may change for each case.
! ------------------------------------------------------------------------------
#:def zetas_declaration(ZETAS)
   #:if ZETAS == "PCSAFT-ZETAS"
      real(8) :: zetas(0:3)
      real(8) :: rho
      real(8) :: eta
   #:endif
#:enddef zetas_declaration

! ------------------------------------------------------------------------------
! Code
!
! SAFT's zetas implementations, add new ones here in the if structure.
! ------------------------------------------------------------------------------
#:def zetas(ZETAS)
   #:if ZETAS == "PCSAFT-ZETAS"
      rho = n_tot * N_AVO / (V * 1.0e27_8)  ! Number density [1/A^3]
      
      zetas = 0.0_8
      do k = 0, 3
         zetas(k) = rho * (PI / 6.0_8) * sum(x * m * (d**k))
      end do

      eta = 1.0_8 - zetas(3)
   #:endif
#:enddef zetas
