max – yaeos
max Interface
MPL
6 statements
Source File
public interface max
Calls
Module Procedures
public elemental function max_dd(v1, v2) result(v3)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: v1
type(hyperdual), intent(in) :: v2
Return Value type(hyperdual)
public elemental function max_ddd(v1, v2, v3) result(v4)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: v1
type(hyperdual), intent(in) :: v2
type(hyperdual), intent(in) :: v3
Return Value type(hyperdual)
public elemental function max_dr(v1, v2) result(v3)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: v1
real(kind=pr), intent(in) :: v2
Return Value type(hyperdual)
public elemental function max_rd(v1, v2) result(v3)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: v1
type(hyperdual), intent(in) :: v2
Return Value type(hyperdual)
Call graph
max calls max_dd, max_ddd, max_dr, max_rd