newton – yaeos
newton Interface
MPL
3 statements
Source File
public interface newton
Calls
Called by
Module Procedures
public subroutine newton_1d(f, x, tol, max_iters, failed)
Arguments
Type Intent Optional Attributes Name
procedure(f_1d) :: f
real(kind=pr), intent(inout) :: x
real(kind=pr), intent(in) :: tol
integer, intent(in) :: max_iters
logical, intent(out) :: failed
Call graph
newton calls newton_1d
volume calls newton
binary_llv_from_cep calls volume
critical_line calls volume, look_for_cep
critical_point calls volume
lnphi_pt calls volume
pure_saturation_line calls volume
saturation_pressure calls volume, lnphi_pt, solve_tp
saturation_temperature calls volume, lnphi_pt, solve_tp
stability_check calls volume
find_hpl calls lnphi_pt, pt_envelope_2ph
find_llcl calls lnphi_pt
get_critical_constants calls critical_point, psat_pure
look_for_cep calls stability_check
pt_f_np calls lnphi_pt
pt_f_three_phases calls lnphi_pt
px_f_np calls lnphi_pt
px_f_three_phases calls lnphi_pt
refit_rkpr_k calls pure_saturation_line, psat_pure
saturation_tp calls lnphi_pt
tx_f_np calls lnphi_pt
init_pcsaft calls get_critical_constants
psat_pure calls diff
px_envelope_2ph calls foo
rkpr calls refit_rkpr_k
solve_generalized_point calls pt_f_np
solve_mp_flash_point calls pt_f_np
solve_point calls px_f_np, tx_f_np, pt_f_three_phases, pt_f_np, px_f_three_phases
tx_envelope_2ph calls foo
create_generalized_isoz_line calls solve_generalized_point
pt_envelope calls solve_point
pt_envelope_3ph calls solve_point
pt_mp_flash calls solve_mp_flash_point
px_envelope calls solve_point
px_envelope_3ph calls solve_point
solve_tp calls wrap
tx_envelope calls solve_point
pt_envelope_2ph calls pt_envelope