operator (**) – Yaeos
operator (**) Interface
MIT
5 statements
Source File
public interface operator (**)
Calls
Contents
Module Procedures
PowerHyperDualInt PowerHyperDualHyperDual PowerHyperDualReal
Module Procedures
public elemental function PowerHyperDualInt(v1, v2) result(v3)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: v1
integer, intent(in) :: v2
Return Value type(hyperdual)
public elemental function PowerHyperDualHyperDual(v1, v2) result(v3)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: v1
type(hyperdual), intent(in) :: v2
Return Value type(hyperdual)
public elemental function PowerHyperDualReal(v1, v2) result(v3)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: v1
real(kind=pr), intent(in) :: v2
Return Value type(hyperdual)
Call graph
operator (ASTERISKASTERISK) calls powerhyperdualint, powerhyperdualreal, powerhyperdualhyperdual
powerhyperdualhyperdual calls loghyperdual, exphyperdual