operator (.gt.) – yaeos
operator (.gt.) Interface
MPL
7 statements
Source File
public interface operator (.gt.)
Calls
Module Procedures
public function gt_dd(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: lhs
type(hyperdual), intent(in) :: rhs
Return Value logical
public function gt_dr(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: lhs
real(kind=pr), intent(in) :: rhs
Return Value logical
public function gt_rd(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: lhs
type(hyperdual), intent(in) :: rhs
Return Value logical
public function gt_di(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: lhs
integer, intent(in) :: rhs
Return Value logical
public function gt_id(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: lhs
type(hyperdual), intent(in) :: rhs
Return Value logical
Call graph
operator (.gt.) calls gt_dd, gt_di, gt_dr, gt_id, gt_rd