operator (*) – Yaeos
operator (*) Interface
MPL
7 statements
Source File
public interface operator (*)
Calls
Contents
Module Procedures
MultiplyHyperDualHyperDual MultiplyHyperDualReal MultiplyRealHyperDual MultiplyHyperDualInt MultiplyIntHyperDual
Module Procedures
public elemental function MultiplyHyperDualHyperDual(v1, v2) result(v3)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: v1
type(hyperdual), intent(in) :: v2
Return Value type(hyperdual)
public elemental function MultiplyHyperDualReal(v1, v2) result(v3)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: v1
real(kind=pr), intent(in) :: v2
Return Value type(hyperdual)
public elemental function MultiplyRealHyperDual(v1, v2) result(v3)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: v1
type(hyperdual), intent(in) :: v2
Return Value type(hyperdual)
public elemental function MultiplyHyperDualInt(v1, v2) result(v3)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: v1
integer, intent(in) :: v2
Return Value type(hyperdual)
public elemental function MultiplyIntHyperDual(v1, v2) result(v3)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: v1
type(hyperdual), intent(in) :: v2
Return Value type(hyperdual)
Call graph
operator (ASTERISK) calls multiplyhyperdualhyperdual, multiplyhyperdualreal, multiplyrealhyperdual, multiplyhyperdualint, multiplyinthyperdual