operator (.eq.) – yaeos
operator (.eq.) Interface
MPL
7 statements
Source File
public interface operator (.eq.)
Calls
Module Procedures
public function eq_dd(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: lhs
type(hyperdual), intent(in) :: rhs
Return Value logical
public elemental function eq_dr(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: lhs
real(kind=pr), intent(in) :: rhs
Return Value logical
public elemental function eq_rd(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: lhs
type(hyperdual), intent(in) :: rhs
Return Value logical
public function eq_di(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: lhs
integer, intent(in) :: rhs
Return Value logical
public function eq_id(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: lhs
type(hyperdual), intent(in) :: rhs
Return Value logical
Call graph
operator (.eq.) calls eq_dd, eq_di, eq_dr, eq_id, eq_rd