operator (.le.) – yaeos
operator (.le.) Interface
MPL
7 statements
Source File
public interface operator (.le.)
Calls
Module Procedures
public function le_dd(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: lhs
type(hyperdual), intent(in) :: rhs
Return Value logical
public function le_dr(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: lhs
real(kind=pr), intent(in) :: rhs
Return Value logical
public function le_rd(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: lhs
type(hyperdual), intent(in) :: rhs
Return Value logical
public function le_di(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: lhs
integer, intent(in) :: rhs
Return Value logical
public function le_id(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: lhs
type(hyperdual), intent(in) :: rhs
Return Value logical
Call graph
operator (.le.) calls le_dd, le_di, le_dr, le_id, le_rd