operator (.lt.) – Yaeos
operator (.lt.) Interface
MIT
7 statements
Source File
public interface operator (.lt.)
Calls
Contents
Module Procedures
lt_dd lt_dr lt_rd lt_di lt_id
Module Procedures
public function lt_dd(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: lhs
type(hyperdual), intent(in) :: rhs
Return Value logical
public function lt_dr(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: lhs
real(kind=pr), intent(in) :: rhs
Return Value logical
public function lt_rd(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
real(kind=pr), intent(in) :: lhs
type(hyperdual), intent(in) :: rhs
Return Value logical
public function lt_di(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
type(hyperdual), intent(in) :: lhs
integer, intent(in) :: rhs
Return Value logical
public function lt_id(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: lhs
type(hyperdual), intent(in) :: rhs
Return Value logical
Call graph
operator (.lt.) calls lt_di, lt_dr, lt_id, lt_rd, lt_dd