[build-system]
build-backend = "mesonpy"
requires = [
    "meson-python>=0.15.0",
    "numpy",
    "fpm",
    "ninja; platform_system!='Windows'", 
    "wheel"
]


[project]
name = "yaeos"
description = "Thermodynamic modelling with Equations of State"
readme = "README.md"
dependencies = ["IPython", "numpy", "scipy", "pandas", "intersect", "matplotlib"]
version = "4.5.4"
requires-python = ">=3.10"


[tool.black]
line-length = 79
target-version = ["py310"]


[tool.pytest.ini_options]
markers = [
    "marker_name: marker_description",
]


[tool.cibuildwheel]
build = ["cp310-*", "cp311-*", "cp312-*", "cp313-*", "cp314-*"]
skip = ["*-manylinux_i686", "*-musllinux_*", "*-win32"]
manylinux-x86_64-image = "manylinux_2_28"

[tool.cibuildwheel.linux]
# before-all = "yum -y install lapack-devel"
# before-all = "apt-get update && apt-get install -y gfortran"
# before-all = "dnf update -y && dnf install -y lapack-devel blas-devel gcc-gfortran"
before-all = """
dnf install -y epel-release && \\
dnf install -y lapack-devel blas-devel gcc-toolset-15-gcc-gfortran && \\
source /opt/rh/gcc-toolset-15/enable && echo 'source /opt/rh/gcc-toolset-15/enable' >> ~/.bashrc
"""

[tool.cibuildwheel.linux.environment]
# These variables will strictly apply to the Linux container runs
CC = "gcc-15"
CXX = "g++-15"
FPM_FC = "gfortran-15"
FC = "gfortran-15"
F77 = "gfortran-15"
F90 = "gfortran-15"

PATH = "/opt/rh/gcc-toolset-15/root/usr/bin:$PATH"
LD_LIBRARY_PATH = "/opt/rh/gcc-toolset-15/root/usr/lib64:/opt/rh/gcc-tools"


[tool.cibuildwheel.macos]
before-all = "brew update && brew install lapack"

# [tool.cibuildwheel.windows]
# before-all = """
#     git clone https://github.com/microsoft/vcpkg.git
#     cd vcpkg
#     .\\bootstrap-vcpkg.bat
#     .\\vcpkg install lapack blas
# """
